// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "flycast-jitless",
    defaultLocalization: "en",
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "flycast-jitless",
            targets: ["flycast-jitless"]),
    ],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "flycast-jitless",
            path: "./",
            exclude: [
                "README.md",
                "build/",
                "docs/",
                "fonts/",
                "intl/",
                "resources/",
                "shell/",
                "tests/",
                "tools/",
                "build.sh",
                "CMakeLists.txt",
                "CMakePresets.json",
                "Config.xcconfig",
                "flycast.entitlements",
                "LICENSE",
                "MoltenVK_Compatibility.md",
                "core/deps/breakpad/",
                "core/deps/Syphon/",
                "core/deps/"
            ],
            sources:
                Consts.hw,
            publicHeadersPath: "core/",
            cSettings: Consts.include.map{.headerSearchPath($0)}
        ),
        .testTarget(
            name: "flycast-jitlessTests",
            dependencies: ["flycast-jitless"]
        ),
    ]
)

enum Consts {

    static let hw: [String] = [
		"core/hw/hwreg.h",
        "core/hw/aica/aica.cpp",
        "core/hw/aica/aica.h",
        "core/hw/aica/aica_if.cpp",
        "core/hw/aica/aica_if.h",
        "core/hw/aica/aica_mem.cpp",
        "core/hw/aica/aica_mem.h",
        "core/hw/aica/dsp.cpp",
        "core/hw/aica/dsp.h",
        "core/hw/aica/dsp_arm32.cpp",
        "core/hw/aica/dsp_arm64.cpp",
        "core/hw/aica/dsp_interp.cpp",
        "core/hw/aica/dsp_x64.cpp",
        "core/hw/aica/dsp_x86.cpp",
        "core/hw/aica/sgc_if.cpp",
        "core/hw/aica/sgc_if.h",
        "core/hw/arm7/arm7.cpp",
        "core/hw/arm7/arm7.h",
        "core/hw/arm7/arm_mem.cpp",
        "core/hw/arm7/arm_mem.h",
        "core/hw/arm7/arm7_rec_arm32.cpp",
        "core/hw/arm7/arm7_rec_arm64.cpp",
        "core/hw/arm7/arm7_rec_x64.cpp",
        "core/hw/arm7/arm7_rec.cpp",
        "core/hw/arm7/arm7_rec.h",
        "core/hw/arm7/arm-new.h",
        "core/hw/bba/bba.h",
        "core/hw/bba/bba.cpp",
        "core/hw/bba/rtl8139c.h",
        "core/hw/bba/rtl8139c.cpp",
        "core/hw/flashrom/at93cxx.cpp",
        "core/hw/flashrom/at93cxx.h",
        "core/hw/flashrom/flashrom.cpp",
        "core/hw/flashrom/flashrom.h",
        "core/hw/flashrom/nvmem.cpp",
        "core/hw/flashrom/nvmem.h",
        "core/hw/flashrom/x76f100.cpp",
        "core/hw/flashrom/x76f100.h",
        "core/hw/gdrom/gdrom_if.h",
        "core/hw/gdrom/gdrom_response.cpp",
        "core/hw/gdrom/gdromv3.cpp",
        "core/hw/gdrom/gdromv3.h",
        "core/hw/holly/holly_intc.cpp",
        "core/hw/holly/holly_intc.h",
        "core/hw/holly/sb.cpp",
        "core/hw/holly/sb.h",
        "core/hw/holly/sb_mem.cpp",
        "core/hw/holly/sb_mem.h",
        "core/hw/maple/maple_cfg.cpp",
        "core/hw/maple/maple_cfg.h",
        "core/hw/maple/maple_devs.cpp",
        "core/hw/maple/maple_devs.h",
        "core/hw/maple/maple_helper.cpp",
        "core/hw/maple/maple_helper.h",
        "core/hw/maple/maple_if.cpp",
        "core/hw/maple/maple_if.h",
        "core/hw/maple/maple_jvs.cpp",
        "core/hw/mem/addrspace.cpp",
        "core/hw/mem/addrspace.h",
        "core/hw/mem/mem_watch.cpp",
        "core/hw/mem/mem_watch.h",
        "core/hw/modem/modem.cpp",
        "core/hw/modem/modem.h",
        "core/hw/modem/modem_regs.h",
        "core/hw/naomi/awave_regs.h",
        "core/hw/naomi/awcartridge.cpp",
        "core/hw/naomi/awcartridge.h",
        "core/hw/naomi/decrypt.cpp",
        "core/hw/naomi/decrypt.h",
        "core/hw/naomi/gdcartridge.cpp",
        "core/hw/naomi/gdcartridge.h",
        "core/hw/naomi/m1cartridge.cpp",
        "core/hw/naomi/m1cartridge.h",
        "core/hw/naomi/m4cartridge.cpp",
        "core/hw/naomi/m4cartridge.h",
        "core/hw/naomi/multiboard.h",
        "core/hw/naomi/multiboard.cpp",
        "core/hw/naomi/naomi_cart.cpp",
        "core/hw/naomi/naomi_cart.h",
        "core/hw/naomi/naomi_flashrom.cpp",
        "core/hw/naomi/naomi_flashrom.h",
        "core/hw/naomi/naomi_m3comm.cpp",
        "core/hw/naomi/naomi_m3comm.h",
        "core/hw/naomi/naomi.cpp",
        "core/hw/naomi/naomi.h",
        "core/hw/naomi/naomi_regs.h",
        "core/hw/naomi/naomi_roms.cpp",
        "core/hw/naomi/naomi_roms.h",
        "core/hw/naomi/naomi_roms_input.h",
        "core/hw/naomi/netdimm.cpp",
        "core/hw/naomi/netdimm.h",
        "core/hw/naomi/card_reader.h",
        "core/hw/naomi/card_reader.cpp",
        "core/hw/naomi/touchscreen.h",
        "core/hw/naomi/touchscreen.cpp",
        "core/hw/naomi/printer.h",
        "core/hw/naomi/printer.cpp",
        "core/hw/naomi/systemsp.h",
        "core/hw/naomi/systemsp.cpp",
        "core/hw/naomi/hopper.h",
        "core/hw/naomi/hopper.cpp",
        "core/hw/pvr/elan.cpp",
        "core/hw/pvr/elan.h",
        "core/hw/pvr/elan_struct.h",
        "core/hw/pvr/pvr.cpp",
        "core/hw/pvr/pvr.h",
        "core/hw/pvr/pvr_mem.cpp",
        "core/hw/pvr/pvr_mem.h",
        "core/hw/pvr/pvr_regs.cpp",
        "core/hw/pvr/pvr_regs.h",
        "core/hw/pvr/pvr_sb_regs.cpp",
        "core/hw/pvr/pvr_sb_regs.h",
        "core/hw/pvr/Renderer_if.cpp",
        "core/hw/pvr/Renderer_if.h",
        "core/hw/pvr/spg.cpp",
        "core/hw/pvr/spg.h",
        "core/hw/pvr/ta_const_df.h",
        "core/hw/pvr/ta.cpp",
        "core/hw/pvr/ta_ctx.cpp",
        "core/hw/pvr/ta_ctx.h",
        "core/hw/pvr/ta.h",
        "core/hw/pvr/ta_structs.h",
        "core/hw/pvr/ta_util.cpp",
        "core/hw/pvr/ta_vtx.cpp",
        "core/hw/sh4/dyna/blockmanager.cpp",
        "core/hw/sh4/dyna/blockmanager.h",
        "core/hw/sh4/dyna/decoder.cpp",
        "core/hw/sh4/dyna/decoder.h",
        "core/hw/sh4/dyna/decoder_opcodes.h",
        "core/hw/sh4/dyna/driver.cpp",
        "core/hw/sh4/dyna/ngen.h",
        "core/hw/sh4/dyna/shil_canonical.h",
        "core/hw/sh4/dyna/shil.cpp",
        "core/hw/sh4/dyna/shil.h",
        "core/hw/sh4/dyna/ssa.cpp",
        "core/hw/sh4/dyna/ssa.h",
        "core/hw/sh4/dyna/ssa_regalloc.h",
        "core/hw/sh4/fsca-table.h",
        "core/hw/sh4/interpr/sh4_fpu.cpp",
        "core/hw/sh4/interpr/sh4_interpreter.cpp",
		"core/hw/sh4/interpr/sh4_opcodes.cpp",
		"core/hw/sh4/interpr/sh4_opcodes.h",
		"core/hw/sh4/modules/bsc.cpp",
		"core/hw/sh4/modules/ccn.cpp",
		"core/hw/sh4/modules/ccn.h",
		"core/hw/sh4/modules/cpg.cpp",
		"core/hw/sh4/modules/dmac.cpp",
		"core/hw/sh4/modules/dmac.h",
        "core/hw/sh4/modules/fastmmu.cpp",
		"core/hw/sh4/modules/intc.cpp",
		"core/hw/sh4/modules/mmu.cpp",
		"core/hw/sh4/modules/mmu.h",
		"core/hw/sh4/modules/modules.h",
		"core/hw/sh4/modules/rtc.cpp",
		"core/hw/sh4/modules/serial.cpp",
		"core/hw/sh4/modules/tmu.cpp",
		"core/hw/sh4/modules/ubc.cpp",
		"core/hw/sh4/modules/wince.h",
		"core/hw/sh4/sh4_cache.h",
		"core/hw/sh4/sh4_cycles.cpp",
		"core/hw/sh4/sh4_cycles.h",
		"core/hw/sh4/sh4_core.h",
		"core/hw/sh4/sh4_core_regs.cpp",
		"core/hw/sh4/sh4_if.h",
		"core/hw/sh4/sh4_interpreter.h",
		"core/hw/sh4/sh4_interrupts.cpp",
		"core/hw/sh4/sh4_interrupts.h",
		"core/hw/sh4/sh4_mem.cpp",
		"core/hw/sh4/sh4_mem.h",
		"core/hw/sh4/sh4_mmr.cpp",
		"core/hw/sh4/sh4_mmr.h",
		"core/hw/sh4/sh4_opcode_list.cpp",
		"core/hw/sh4/sh4_opcode_list.h",
		"core/hw/sh4/sh4_rom.cpp",
		"core/hw/sh4/sh4_rom.h",
		"core/hw/sh4/sh4_sched.cpp",
		"core/hw/sh4/sh4_sched.h",
		"core/hw/sh4/storeq.cpp"
    ]

    static let rend_vulkan: [String] = [
        "core/rend/vulkan/vk_context_lr.cpp",
		"core/rend/vulkan/vk_context_lr.h"
    ]

    static let pico: [String] = [
    	"core/deps/picotcp/include/arch/pico_arm9.h",
		"core/deps/picotcp/include/arch/pico_atsamd21j18.h",
		"core/deps/picotcp/include/arch/pico_avr.h",
		"core/deps/picotcp/include/arch/pico_cortex_m.h",
		"core/deps/picotcp/include/arch/pico_dos.h",
		"core/deps/picotcp/include/arch/pico_esp8266.h",
		"core/deps/picotcp/include/arch/pico_generic_gcc.h",
		"core/deps/picotcp/include/arch/pico_linux.h",
		"core/deps/picotcp/include/arch/pico_mbed.h",
		"core/deps/picotcp/include/arch/pico_msp430.h",
		"core/deps/picotcp/include/arch/pico_msvc.h",
		"core/deps/picotcp/include/arch/pico_none.h",
		"core/deps/picotcp/include/arch/pico_pic24.h",
		"core/deps/picotcp/include/arch/pico_pic32.h",
		"core/deps/picotcp/include/arch/pico_posix.h",
		"core/deps/picotcp/include/heap.h",
		"core/deps/picotcp/include/pico_addressing.h",
		"core/deps/picotcp/include/pico_config.h",
		"core/deps/picotcp/include/pico_constants.h",
		"core/deps/picotcp/include/pico_defines.h",
		"core/deps/picotcp/include/pico_defines_msvc.h",
		"core/deps/picotcp/include/pico_device.h",
		"core/deps/picotcp/include/pico_eth.h",
		"core/deps/picotcp/include/pico_frame.h",
		"core/deps/picotcp/include/pico_md5.h",
		"core/deps/picotcp/include/pico_module_eth.h",
		"core/deps/picotcp/include/pico_protocol.h",
		"core/deps/picotcp/include/pico_queue.h",
		"core/deps/picotcp/include/pico_socket.h",
		"core/deps/picotcp/include/pico_socket_multicast.h",
		"core/deps/picotcp/include/pico_stack.h",
		"core/deps/picotcp/include/pico_tree.h",
		"core/deps/picotcp/modules/pico_arp.c",
		"core/deps/picotcp/modules/pico_dev_ppp.c",
		"core/deps/picotcp/modules/pico_dhcp_common.c",
		"core/deps/picotcp/modules/pico_dhcp_common.h",
		"core/deps/picotcp/modules/pico_dhcp_server.c",
		"core/deps/picotcp/modules/pico_dhcp_server.h",
		"core/deps/picotcp/modules/pico_dns_client.c",
		"core/deps/picotcp/modules/pico_dns_common.c",
		"core/deps/picotcp/modules/pico_ethernet.c",
		"core/deps/picotcp/modules/pico_fragments.c",
		"core/deps/picotcp/modules/pico_icmp4.c",
		"core/deps/picotcp/modules/pico_ipv4.c",
		"core/deps/picotcp/modules/pico_socket_tcp.c",
		"core/deps/picotcp/modules/pico_socket_udp.c",
		"core/deps/picotcp/modules/pico_strings.c",
		"core/deps/picotcp/modules/pico_tcp.c",
		"core/deps/picotcp/modules/pico_udp.c",
		"core/deps/picotcp/stack/pico_device.c",
		"core/deps/picotcp/stack/pico_frame.c",
		"core/deps/picotcp/stack/pico_md5.c",
		"core/deps/picotcp/stack/pico_protocol.c",
		"core/deps/picotcp/stack/pico_socket.c",
		"core/deps/picotcp/stack/pico_socket_multicast.c",
		"core/deps/picotcp/stack/pico_stack.c",
		"core/deps/picotcp/stack/pico_tree.c",
    ]

    static let sevenZip: [String] = [
        "core/deps/lzma/7zArcIn.c",
        "core/deps/lzma/7zBuf.c",
        "core/deps/lzma/7zCrc.c",
        "core/deps/lzma/7zCrcOpt.c",
        "core/deps/lzma/7zDec.c",
        "core/deps/lzma/7zFile.c",
        "core/deps/lzma/7zStream.c",
        "core/deps/lzma/Alloc.c",
        "core/deps/lzma/Bcj2.c",
        "core/deps/lzma/Bra86.c",
        "core/deps/lzma/Bra.c",
        "core/deps/lzma/BraIA64.c",
        "core/deps/lzma/CpuArch.c",
        "core/deps/lzma/Delta.c",
        "core/deps/lzma/LzFind.c",
        "core/deps/lzma/Lzma2Dec.c",
        "core/deps/lzma/Lzma86Dec.c",
        "core/deps/lzma/Lzma86Enc.c",
        "core/deps/lzma/LzmaDec.c",
        "core/deps/lzma/LzmaEnc.c",
        "core/deps/lzma/LzmaLib.c",
        "core/deps/lzma/Sort.c",
    ]

    static let deps: [String] = [
        "core/deps/xbrz/xbrz.cpp",
        "core/deps/md5/md5.cpp",
    ]

    static let include: [String] = [
        "core/",
        "core/deps/libretro-common/include",
		"core/log/",
        "core/audio/",
        "core/oslib/",
        "core/lua/",
        "core/rend/vulkan/",
    ]

    enum Libretro {

        static let common: [String] = [
            "core/deps/libretro-common/memmap/memalign.c",
            "core/deps/libretro-common/file/file_path.c",
            "core/deps/libretro-common/vfs/vfs_implementation.c",
            "core/deps/libretro-common/encodings/encoding_utf.c",
            "core/deps/libretro-common/compat/compat_strl.c",
            "core/deps/libretro-common/compat/fopen_utf8.c",
            "core/deps/libretro-common/compat/compat_strcasestr.c",
            "core/deps/libretro-common/file/retro_dirent.c",
            "core/deps/libretro-common/string/stdstring.c",
        ]

        static let openGL: [String] = [
			"core/deps/libretro-common/glsm/glsm.c",
			"core/deps/libretro-common/glsym/rglgen.c",
            "core/deps/libretro-common/glsym/glsym_es3.c",
        ]

        static let libretro: [String] = [
            "shell/libretro/audiostream.cpp",
            "shell/libretro/keyboard_map.h",
            "shell/libretro/libretro_core_option_defines.h",
            "shell/libretro/libretro_core_options_intl.h",
            "shell/libretro/libretro_core_options.h",
            "shell/libretro/libretro.cpp",
            "shell/libretro/LogManager.cpp",
            "shell/libretro/LogManager.h",
            "shell/libretro/option.cpp",
            "shell/libretro/oslib.cpp",
            "shell/libretro/vmu_xhair.cpp",
            "shell/libretro/oslib_apple.mm"
        ]
    }

    static let archive: [String] = [
        "core/archive/7zArchive.cpp",
		"core/archive/7zArchive.h",
		"core/archive/archive.cpp",
		"core/archive/archive.h",
		"core/archive/rzip.cpp",
		"core/archive/rzip.h",
		"core/archive/ZipArchive.cpp",
		"core/archive/ZipArchive.h",
		"core/cfg/option.h",
    ]

    static let imgRead: [String] = [
        "core/imgread/cdi.cpp",
		"core/imgread/cdio.cpp",
		"core/imgread/chd.cpp",
		"core/imgread/common.cpp",
		"core/imgread/common.h",
		"core/imgread/cue.cpp",
		"core/imgread/gdi.cpp",
		"core/imgread/ImgReader.cpp",
		"core/imgread/iso9660.h",
		"core/imgread/isofs.cpp",
		"core/imgread/isofs.h",
    ]

    static let linux: [String] = [
        "core/linux/common.cpp",
        "core/linux/context.cpp",
        "core/linux/posix_vmem.cpp",
        "core/linux/unwind_info.cpp",
    ]

    static let network: [String] = [
        "core/network/alienfnt_modem.cpp",
		"core/network/alienfnt_modem.h",
		"core/network/dns.cpp",
		"core/network/ggpo.cpp",
		"core/network/ggpo.h",
		"core/network/miniupnp.cpp",
		"core/network/miniupnp.h",
		"core/network/naomi_network.cpp",
		"core/network/naomi_network.h",
		"core/network/net_handshake.cpp",
		"core/network/net_handshake.h",
		"core/network/net_platform.h",
		"core/network/output.cpp",
		"core/network/output.h",
		"core/network/picoppp.cpp",
		"core/network/picoppp.h",
		"core/network/netservice.cpp",
		"core/network/netservice.h",
		"core/network/dcnet.cpp",
		"core/network/dcnet.h",
    ]

    static let oslib: [String] = [
        "core/audio/audiostream.h",
		"core/oslib/directory.h",
		"core/oslib/host_context.h",
		"core/oslib/oslib.h",
		"core/oslib/resources.cpp",
		"core/oslib/resources.h",
		"core/oslib/storage.cpp",
		"core/oslib/storage.h",
		"core/oslib/unwind_info.h",
		"core/oslib/virtmem.h",
		"core/lua/lua.cpp",
		"core/lua/lua.h",
    ]

    enum Profiler {
        static let dc: [String] = [
            "core/profiler/dc_profiler.cpp",
            "core/profiler/dc_profiler.h",
        ]

        static let fc: [String] = [
            "core/profiler/fc_profiler.cpp",
            "core/profiler/fc_profiler.h",
        ]
    }

    static let reios: [String] = [
        "core/reios/descrambl.cpp",
		"core/reios/descrambl.h",
		"core/reios/gdrom_hle.cpp",
		"core/reios/gdrom_hle.h",
		"core/reios/reios.cpp",
		"core/reios/reios.h",
		"core/reios/reios_elf.cpp",
		"core/reios/reios_elf.h",
    ]

    static let achievements: [String] = [
        "core/achievements/achievements.cpp",
        "core/achievements/achievements.h",
    ]

    static let wsi: [String] = [
        "core/wsi/context.h",
		"core/wsi/libretro.cpp",
		"core/wsi/libretro.h",
		"core/wsi/switcher.cpp",
    ]

    static let openGL: [String] = [
        "core/wsi/egl.cpp",
        "core/wsi/egl.h",
        "core/wsi/gl_context.cpp",
        "core/wsi/gl_context.h",
        "core/wsi/osx.cpp",
        "core/wsi/osx.h",
        "core/wsi/sdl.cpp",
        "core/wsi/sdl.h",
        "core/rend/gles/glcache.h",
        "core/rend/gles/gldraw.cpp",
        "core/rend/gles/gles.cpp",
        "core/rend/gles/gles.h",
        "core/rend/gles/gltex.cpp",
        "core/rend/gles/quad.cpp",
        "core/rend/gles/postprocess.cpp",
        "core/rend/gles/postprocess.h",
        "core/rend/gles/naomi2.cpp",
        "core/rend/gles/naomi2.h",
    ]

    static let core: [String] = [
		"core/build.h",
		"core/cheats.cpp",
		"core/cheats.h",
		"core/emulator.h",
		"core/nullDC.cpp",
		"core/serialize.cpp",
		"core/serialize.h",
		"core/stdclass.cpp",
		"core/stdclass.h",
		"core/types.h",
		"core/debug/gdb_server.h",
    ]

    static let rend: [String] = [
		"core/rend/CustomTexture.cpp",
		"core/rend/CustomTexture.h",
		"core/rend/osd.cpp",
		"core/rend/osd.h",
		"core/rend/sorter.cpp",
		"core/rend/sorter.h",
		"core/rend/tileclip.h",
		"core/rend/TexCache.cpp",
		"core/rend/TexCache.h",
		"core/rend/texconv.cpp",
		"core/rend/texconv.h",
		"core/rend/norend/norend.cpp",
    ]

    static let vulkan: [String] = [
        "core/rend/vulkan/oit/oit_buffer.h",
        "core/rend/vulkan/oit/oit_drawer.cpp",
        "core/rend/vulkan/oit/oit_drawer.h",
        "core/rend/vulkan/oit/oit_pipeline.cpp",
        "core/rend/vulkan/oit/oit_pipeline.h",
        "core/rend/vulkan/oit/oit_renderer.cpp",
        "core/rend/vulkan/oit/oit_renderpass.cpp",
        "core/rend/vulkan/oit/oit_renderpass.h",
        "core/rend/vulkan/oit/oit_shaders.cpp",
        "core/rend/vulkan/oit/oit_shaders.h",
        "core/rend/vulkan/adreno.cpp",
        "core/rend/vulkan/buffer.cpp",
        "core/rend/vulkan/buffer.h",
        "core/rend/vulkan/commandpool.cpp",
        "core/rend/vulkan/commandpool.h",
        "core/rend/vulkan/compiler.cpp",
        "core/rend/vulkan/compiler.h",
        "core/rend/vulkan/drawer.cpp",
        "core/rend/vulkan/drawer.h",
        "core/rend/vulkan/pipeline.cpp",
        "core/rend/vulkan/pipeline.h",
        "core/rend/vulkan/quad.cpp",
        "core/rend/vulkan/quad.h",
        "core/rend/vulkan/shaders.cpp",
        "core/rend/vulkan/shaders.h",
        "core/rend/vulkan/texture.cpp",
        "core/rend/vulkan/texture.h",
        "core/rend/vulkan/utils.h",
        "core/rend/vulkan/vmallocator.cpp",
        "core/rend/vulkan/vmallocator.h",
        "core/rend/vulkan/overlay.cpp",
        "core/rend/vulkan/overlay.h",
        "core/rend/vulkan/vulkan_context.h",
        "core/rend/vulkan/vulkan.h",
        "core/rend/vulkan/vulkan_renderer.cpp",
    ]

    static let vixl: [String] = [
        "core/deps/vixl/aarch64/abi-aarch64.h",
        "core/deps/vixl/aarch64/assembler-aarch64.cc",
        "core/deps/vixl/aarch64/assembler-aarch64.h",
        "core/deps/vixl/aarch64/assembler-sve-aarch64.cc",
        "core/deps/vixl/aarch64/constants-aarch64.h",
        "core/deps/vixl/aarch64/instructions-aarch64.cc",
        "core/deps/vixl/aarch64/instructions-aarch64.h",
        "core/deps/vixl/aarch64/macro-assembler-aarch64.cc",
        "core/deps/vixl/aarch64/macro-assembler-aarch64.h",
        "core/deps/vixl/aarch64/macro-assembler-sve-aarch64.cc",
        "core/deps/vixl/aarch64/operands-aarch64.cc",
        "core/deps/vixl/aarch64/operands-aarch64.h",
        "core/deps/vixl/aarch64/registers-aarch64.cc",
        "core/deps/vixl/aarch64/registers-aarch64.h",
        "core/deps/vixl/aarch64/pointer-auth-aarch64.cc",
        "core/deps/vixl/aarch64/simulator-constants-aarch64.h",
        "core/deps/vixl/assembler-base-vixl.h",
        "core/deps/vixl/code-buffer-vixl.cc",
        "core/deps/vixl/code-buffer-vixl.h",
        "core/deps/vixl/code-generation-scopes-vixl.h",
        "core/deps/vixl/compiler-intrinsics-vixl.cc",
        "core/deps/vixl/compiler-intrinsics-vixl.h",
        "core/deps/vixl/cpu-features.cc",
        "core/deps/vixl/cpu-features.h",
        "core/deps/vixl/globals-vixl.h",
        "core/deps/vixl/invalset-vixl.h",
        "core/deps/vixl/macro-assembler-interface.h",
        "core/deps/vixl/platform-vixl.h",
        "core/deps/vixl/pool-manager.h",
        "core/deps/vixl/pool-manager-impl.h",
        "core/deps/vixl/utils-vixl.cc",
        "core/deps/vixl/utils-vixl.h",
        "core/rec-ARM64/rec_arm64.cpp",
        "core/rec-ARM64/arm64_regalloc.h",
    ]
}
