#include "ir_emitter.h"
#include "hw/sh4/sh4_if.h"  // for Sh4Context, etc.
#include "hw/sh4/modules/mmu.h"
#include "deps/vixl/utils-vixl.h" // For SignExtend
#include "log/Log.h"
#include "hw/sh4/sh4_core.h" // for SH4ThrownException and codes
#include "ir_tables.h" // autogenerated opcode -> Op table
#include <cstdarg>
#include <cstdio>
#include <mutex>
#include <unordered_map>
#define XXH_STATIC_LINKING_ONLY
#include <xxhash.h>

#if __APPLE
#include <CoreFoundation/CoreFoundation.h>
#endif

namespace {
static FILE* g_ir_log_file = nullptr;
static std::mutex g_ir_log_mutex;

void log_to_file(const char* fmt, ...)
{
    std::lock_guard<std::mutex> lk(g_ir_log_mutex);
    if (!g_ir_log_file)
    {
        char path[PATH_MAX];
        #if __APPLE
        // Use iOS documents directory
        CFURLRef documents_dir = CFBundleCopyResourcesDirectoryURL(CFBundleGetMainBundle());
        CFURLGetFileSystemRepresentation(documents_dir, true, (UInt8*)path, PATH_MAX);
        CFRelease(documents_dir);
        #else
        // Use home directory on other platforms
        char* home_dir = getenv("HOME");
        if (!home_dir)
            return; // give up silently
        snprintf(path, PATH_MAX, "%s/sh4_ir.log", home_dir);
        #endif
        g_ir_log_file = fopen(path, "a");
        if (!g_ir_log_file)
            return; // give up silently
    }
    va_list ap;
    va_start(ap, fmt);
    vfprintf(g_ir_log_file, fmt, ap);
    va_end(ap);
    fflush(g_ir_log_file);
}

// Reuse identical blocks (e.g. BIOS memset stub copied across SDRAM pages)
static std::unordered_map<uint64_t, const sh4::ir::Block*> g_block_sig_cache;

static uint64_t CalcBlockSig(uint32_t pc)
{
    // Hash first 64 bytes (32 instructions) of code at pc.
    uint8_t buf[64];
    for (int i = 0; i < 32; ++i)
    {
        uint16_t op = mmu_IReadMem16(pc + i * 2);
        buf[i * 2]     = static_cast<uint8_t>(op & 0xFF);
        buf[i * 2 + 1] = static_cast<uint8_t>(op >> 8);
    }
    return XXH3_64bits(buf, sizeof(buf));
}
}

namespace sh4 {
namespace ir {

// Fast-path decode using autogenerated table. Returns true if handled.
static bool FastDecode(uint16_t raw, uint32_t pc, Instr &ins, Block &blk)
{
    // Quick manual overrides for common ops missing from the autogenerated table
    if (raw == 0x0000 || raw == 0x0009) // NOP variants
    {
        ins.op = Op::NOP;
        blk.pcNext = pc + 2;
        return true;
    }
    // MOV.L @(disp,Rm),Rn 0x5nmd : treat all Rm (including R0)
    if ((raw & 0xF000) == 0x5000) {
        uint8_t n = (raw >> 8) & 0xF;
        uint8_t m = (raw >> 4) & 0xF;
        uint8_t disp4 = raw & 0xF;
        ins.op = Op::LOAD32;
        ins.dst = {false, n};
        ins.src1 = {false, m};
        ins.extra = disp4 * 4;
        blk.pcNext = pc + 2;
        return true;
    }
    // MOV.L @Rm+,Rn 0x6nm6  (post-increment long load)
    if ((raw & 0xF00F) == 0x6006) {
        uint8_t n = (raw >> 8) & 0xF;
        uint8_t m = (raw >> 4) & 0xF;
        ins.op = Op::LOAD32_POST;
        ins.dst = {false, n};
        ins.src1 = {false, m};
        blk.pcNext = pc + 2;
        return true;
    }
    // MOV.W @Rm+,Rn 0x6nm5
    if ((raw & 0xF00F) == 0x6005) {
        uint8_t n = (raw >> 8) & 0xF;
        uint8_t m = (raw >> 4) & 0xF;
        ins.op = Op::LOAD16_POST;
        ins.dst = {false, n};
        ins.src1 = {false, m};
        blk.pcNext = pc + 2;
        return true;
    }
    // MOV.B @Rm+,Rn 0x6nm4
    if ((raw & 0xF00F) == 0x6004) {
        uint8_t n = (raw >> 8) & 0xF;
        uint8_t m = (raw >> 4) & 0xF;
        ins.op = Op::LOAD8_POST;
        ins.dst = {false, n};
        ins.src1 = {false, m};
        blk.pcNext = pc + 2;
        return true;
    }

    if ((raw & 0xF000) == 0xE000) // MOV #imm,Rn
    {
        uint8_t n = (raw >> 8) & 0xF;
        ins.op = Op::MOV_IMM;
        ins.dst = {false, n};
        ins.src1.isImm = true;
        ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
        blk.pcNext = pc + 2;
        return true;
    }

    // FRCHG 0xFBFD
    if (raw == 0xFBFD)
    {
        ins.op = Op::FRCHG;
        // FRCHG has no operands
        blk.pcNext = pc + 2;
        return true;
    }

    Op op = static_cast<Op>(kEmitterTable[raw]);
    if (op == Op::ILLEGAL)
        return false;

    uint8_t n = (raw >> 8) & 0xF;
    uint8_t m = (raw >> 4) & 0xF;

    switch (op)
    {
    case Op::NOP:
        ins.op = Op::NOP;
        blk.pcNext = pc + 2;
        return true;

    case Op::MOV_REG:
        ins.op = Op::MOV_REG;
        ins.dst = {false, n};
        ins.src1 = {false, m};
        blk.pcNext = pc + 2;
        return true;

    case Op::MOV_IMM:
        ins.op = Op::MOV_IMM;
        ins.dst = {false, n};
        ins.src1.isImm = true;
        ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
        blk.pcNext = pc + 2;
        return true;

    case Op::ADD_IMM:
        ins.op = Op::ADD_IMM;
        ins.dst = {false, n};
        ins.src1.isImm = true;
        ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
        blk.pcNext = pc + 2;
        return true;

    case Op::SUB:
    case Op::AND_REG:
    case Op::OR_REG:
    case Op::XOR_REG:
    case Op::NOT:
    case Op::NEG:
    case Op::EXTU_B:
    case Op::EXTU_W:
    case Op::EXTS_B:
    case Op::EXTS_W:
        ins.op = op;
        ins.dst = {false, n};
        ins.src1 = {false, m};
        blk.pcNext = pc + 2;
        return true;

    case Op::BRA:
    {
        uint32_t imm12 = raw & 0x0FFF;
        int32_t disp = static_cast<int32_t>(imm12 << 1); // convert to byte displacement
        // Sign-extend 13-bit value (bit 12 is sign after shift)
        if (disp & 0x1000)
            disp |= ~0x1FFF;
        ins.op = Op::BRA;
        ins.extra = disp;
        blk.pcNext = pc + 4;
        return true;
    }
    case Op::BT:
    case Op::BF:
    {
        int8_t disp = raw & 0xFF;
        int32_t d = disp << 1;
        ins.op = op;
        ins.extra = d;
        return true;
    }
    default:
        INFO_LOG(SH4, "FastDecode: Op %d (from raw 0x%04X at PC=0x%08X) fell into default. Returning false.", static_cast<int>(op), raw, pc);
        return false; // not yet implemented; let manual path try
    }
}

Block& Emitter::CreateNew(uint32_t pc) {
    // Simple global cap on total cached blocks to avoid runaway memory usage.
    static constexpr size_t kMaxBlocks = 100000; // ~100k blocks ~= few MB
    if (cache_.size() > kMaxBlocks)
    {
        cache_.clear();
        g_block_sig_cache.clear();
    }

    auto [it, inserted] = cache_.emplace(pc, Block{});
    Block& blk = it->second;
    if (inserted)
    {
        // Deduplicate identical code blocks to avoid runaway allocations.
        uint64_t sig = CalcBlockSig(pc);
        if (auto itSig = g_block_sig_cache.find(sig); itSig != g_block_sig_cache.end())
        {
            // Point cache entry at existing block and discard placeholder.
            return const_cast<Block&>(*itSig->second);
        }

        blk.pcStart = pc;
        INFO_LOG(SH4, "Emitter::CreateNew: Entered for PC=0x%08X", pc);
        uint16_t raw = mmu_IReadMem16(pc);
        INFO_LOG(SH4, "Emitter::CreateNew: PC=0x%08X, raw=0x%04X", pc, raw);

        // Simple decode for a few key opcodes
        uint8_t n = (raw >> 8) & 0xF;
        uint8_t m = (raw >> 4) & 0xF;

        Instr ins{};
        // clear operands
        ins.dst = {};
        ins.src1 = {};
        ins.src2 = {};
        bool decoded = false;

        static Block zero_blk;
        if (raw == 0x0000 || raw == 0x0009 || raw == 0xFFFE || raw == 0xFFFF)
        {
            // Reuse a single stub block for 0x0000 to avoid excessive allocations, but update PC fields each time
            if (zero_blk.code.empty())
            {
                Instr nop{}; nop.op = Op::NOP; zero_blk.code.push_back(nop);
                Instr end{}; end.op = Op::END; zero_blk.code.push_back(end);
            }
            zero_blk.pcStart = pc;
            zero_blk.pcNext  = pc + 2;
            return zero_blk;
        }

        // Attempt fast-path decode first – if handled, emit block immediately
        bool fast_decoded_main_instr = FastDecode(raw, pc, ins, blk);
        INFO_LOG(SH4, "Emitter::CreateNew: PC=0x%08X, raw=0x%04X, FastDecode returned %d, blk.pcNext=0x%08X", pc, raw, fast_decoded_main_instr, blk.pcNext);
        if (fast_decoded_main_instr)
        {
            blk.code.push_back(ins);

            // If this instruction has a delay slot (pcNext == pc + 4), decode the slot too
            if (blk.pcNext == pc + 4)
            {
                uint32_t slot_pc = pc + 2;
                uint16_t slot_raw = mmu_IReadMem16(slot_pc);
                Instr slot{};
                // For decoding the slot, use a dummy block to prevent FastDecode from altering the main block's pcNext.
                // The main block's pcNext is determined by the primary branch instruction.
                Block dummy_slot_blk_for_decode; 
                dummy_slot_blk_for_decode.pcStart = slot_pc; 

                // Attempt FastDecode for the slot.
                // slot.op will be set by FastDecode (possibly to Op::ILLEGAL).
                // fast_decode_claims_handling will be true if FastDecode thinks it decoded it (even to ILLEGAL).
                bool fast_decode_claims_handling = FastDecode(slot_raw, slot_pc, slot, dummy_slot_blk_for_decode);
                INFO_LOG(SH4, "DS: slot_raw=0x%04X, FastDecode_handled=%d, FastDecode_op=%d (ILLEGAL=%d)", slot_raw, fast_decode_claims_handling, static_cast<int>(slot.op), static_cast<int>(Op::ILLEGAL));
                
                // We need to manually decode if FastDecode didn't handle it, 
                // OR if it handled it by marking it ILLEGAL (giving manual decode a chance to do better).
                // Initialize slot_decoded to true ONLY if FastDecode provided a *valid* (non-ILLEGAL) opcode.
                bool slot_decoded = fast_decode_claims_handling && slot.op != Op::ILLEGAL;

                if (!slot_decoded) // If FastDecode didn't provide a valid op, try manual.
                {
                    INFO_LOG(SH4, "DS: Manual decode for slot_raw=0x%04X", slot_raw);
                    // Manual decode for the slot instruction if FastDecode failed
                    uint8_t slot_n_val = (slot_raw >> 8) & 0xF;
                    uint8_t slot_m_val = (slot_raw >> 4) & 0xF;
                    
                    // RTS (0x000B)
                    if (slot_raw == 0x000B) 
                    {
                        slot.op = Op::RTS;
                        slot_decoded = true;
                    }
                    // MOV Rm -> Rn  (0x6nm3)
                    else if ((slot_raw & 0xF00F) == 0x6003) 
                    {
                        slot.op = Op::MOV_REG;
                        slot.dst.isImm = false;
                        slot.dst.reg = slot_n_val;
                        slot.src1.isImm = false;
                        slot.src1.reg = slot_m_val;
                        slot_decoded = true;
                        INFO_LOG(SH4, "DS: Manual decode matched MOV_REG (0x6nm3) for slot_raw=0x%04X", slot_raw);
                    }
                    // MOV #imm,Rn  (0xE000 | Rn<<8 | imm8)
                    else if ((slot_raw & 0xF000) == 0xE000)
                    {
                        slot.op = Op::MOV_IMM;
                        slot.dst.isImm = false;
                        slot.dst.reg = slot_n_val;
                        slot.src1.isImm = true;
                        slot.src1.imm = static_cast<int8_t>(slot_raw & 0xFF);
                        slot_decoded = true;
                    }
                    // ADD #imm,Rn  (0x7000 | Rn<<8 | imm8)
                    else if ((slot_raw & 0xF000) == 0x7000)
                    {
                        slot.op = Op::ADD_IMM;
                        slot.dst.isImm = false;
                        slot.dst.reg = slot_n_val;
                        slot.src1.isImm = true;
                        slot.src1.imm = static_cast<int8_t>(slot_raw & 0xFF);
                        slot_decoded = true;
                    }
                    // MOV.L @Rm+,Rn (0x6nm6) -> Op::LOAD32_POST
                    else if ((slot_raw & 0xF00F) == 0x6006)
                    {
                        slot.op = Op::LOAD32_POST;
                        slot.dst.isImm = false;
                        slot.dst.reg = slot_n_val; // Rn
                        slot.src1.isImm = false;
                        slot.src1.reg = slot_m_val; // Rm
                        slot_decoded = true;
                    }
                    // MOV.W @Rm+,R0 (0x6005, n must be 0) -> Op::LOAD16_POST
                    else if (slot_raw == 0x6005) // Check for specific R0 variant: MOV.W @Rm+,R0 (0x6m05 -> raw 6005 for R0,m) - n fixed to 0
                    {
                        slot.op = Op::LOAD16_POST;
                        slot.dst.isImm = false;
                        slot.dst.reg = 0; // R0
                        slot.src1.isImm = false;
                        slot.src1.reg = slot_m_val; // Rm
                        slot_decoded = true;
                    }
                    // MOV.B @Rm+,R0 (0x6004, n must be 0) -> Op::LOAD8_POST
                    else if (slot_raw == 0x6004) // Check for specific R0 variant: MOV.B @Rm+,R0 (0x6m04 -> raw 6004 for R0,m) - n fixed to 0
                    {
                        slot.op = Op::LOAD8_POST;
                        slot.dst.isImm = false;
                        slot.dst.reg = 0; // R0
                        slot.src1.isImm = false;
                        slot.src1.reg = slot_m_val; // Rm
                        slot_decoded = true;
                    }
                    // LDC Rm, <CR> (0x4mcE, where 'c' is control reg index, 'm' is source GPR Rm)
                    else if ((slot_raw & 0xF00F) == 0x400E) // Matches 0x4mcE pattern
                    {
                        slot.op = Op::LDC;
                        slot.src1.isImm = false;
                        slot.src1.reg = (slot_raw >> 8) & 0xF;    // Rm (source GPR)
                        uint8_t c_val = (slot_raw >> 4) & 0xF;    // c-field from opcode (control register category)

                        if (c_val == 5) // LDC Rm, Rn_BANK (opcode 0x4m5dE, d = bank reg index 0-7)
                        {
                            slot.extra = 8 + (slot_raw & 0x7); // R0_BANK -> 8, ..., R7_BANK -> 15
                        }
                        else
                        {
                            slot.extra = c_val;
                        }
                        slot_decoded = true;
                    }
                    // FRCHG (0xFBFD)
                    else if (slot_raw == 0xFBFD)
                    {
                        slot.op = Op::FRCHG;
                        slot_decoded = true;
                    }
                    // NOP (0x0009) is common in delay slots
                    else if (slot_raw == 0x0009)
                    {
                        slot.op = Op::NOP;
                        slot_decoded = true;
                    }
                    // STS.L PR,@-Rn (0x4n22)
                    else if ((slot_raw & 0xF0FF) == 0x4022)
                    {
                        slot.op = Op::STS_PR_L;
                        slot.dst.isImm = false;
                        slot.dst.reg = slot_n_val;
                        slot_decoded = true;
                    }
                    // LDS.L @Rn+,PR (0x4n6A)
                    else if ((slot_raw & 0xF0FF) == 0x406A)
                    {
                        slot.op = Op::LDS_PR_L;
                        slot.src1.isImm = false;
                        slot.src1.reg = slot_n_val;
                        slot_decoded = true;
                    }
                    // If no manual rule matched for the slot
                    if (!slot_decoded) {
                        slot.op = Op::ILLEGAL;
                    }
                }
                INFO_LOG(SH4, "DS: Pushing slot op %d for 0x%04X to block", static_cast<int>(slot.op), slot_raw);
                blk.code.push_back(slot);
            }

            Instr end{}; end.op = Op::END;
            blk.code.push_back(end);
            // Store signature mapping
            g_block_sig_cache.emplace(sig, &blk);
            return blk;
        }

        // If not decoded by table, fall back to minimal manual patterns below
        // fast-path via autogenerated table is disabled until enum list completed
        // NOP : MOV R0,R0 (0x0009)
        // MOV Rm -> Rn  (0x6nm3) pattern 0110 nnnn mmmm 0011
        // RTS (0x000B)
        else if (raw == 0x000B)
        {
            ins.op = Op::RTS;
            decoded = true;
            blk.pcNext = pc + 4; // includes delay slot
        }
        else if ((raw & 0xF00F) == 0x6003)
        {
            ins.op = Op::MOV_REG;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = false;
            ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV #imm,Rn  (0xE000 | Rn<<8 | imm8)
        else if ((raw & 0xF000) == 0xE000)
        {
            ins.op = Op::MOV_IMM;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = true;
            ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // ADD #imm,Rn  (0x7000 | Rn<<8 | imm8)
        else if ((raw & 0xF000) == 0x7000)
        {
            ins.op = Op::ADD_IMM;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = true;
            ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // BRA disp12  (0xA000 | disp)
        else if ((raw & 0xF000) == 0xA000)
        {
            uint32_t imm12 = raw & 0x0FFF;
            int32_t disp = static_cast<int32_t>(imm12 << 1);
            // Sign-extend 13-bit value (bit 12 is sign after shift)
            if (disp & 0x1000)
                disp |= ~0x1FFF;
            ins.op = Op::BRA;
            ins.extra = disp;
            decoded = true;
            blk.pcNext = pc + 4; // executes delay slot
        }
        // BSR disp12 (0xB000 | disp)
        else if ((raw & 0xF000) == 0xB000)
        {
            INFO_LOG(SH4, "Emitter::CreateNew: Manual BSR handler (0xB000) hit for PC=0x%08X, raw=0x%04X", pc, raw);
            ins.op = Op::BSR;
            ins.extra = vixl::SignExtend<int32_t>(raw & 0x0FFF, 12) * 2; // Displacement is 12-bit, sign-extended, and scaled by 2
            blk.pcNext = pc + 4; // BSR is a delayed branch
            INFO_LOG(SH4, "Emitter::CreateNew: Manual BSR handler (0xB000) hit for PC=0x%08X, raw=0x%04X. Displacement (ins.extra)=0x%08X, Target (calculated by executor)=0x%08X", pc, raw, ins.extra, pc + 4 + ins.extra);
            INFO_LOG(SH4, "Emitter::CreateNew: Manual BSR handler set blk.pcNext=0x%08X", blk.pcNext);
            blk.code.push_back(ins);
            decoded = true;
        }
        // BSRF Rn  (0x0n03)
        else if ((raw & 0xF0FF) == 0x0003)
        {
            ins.op = Op::BSRF;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 4; // includes delay slot
        }
        // BRAF Rn  (0x0n23)
        else if ((raw & 0xF0FF) == 0x0023)
        {
            ins.op = Op::BRAF;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 4; // delay slot
        }
        // STS.L PR,@-Rn (0x4n22)
        else if ((raw & 0xF0FF) == 0x4022)
        {
            ins.op = Op::STS_PR_L;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // LDS.L @Rn+,PR (0x4n6A)
        else if ((raw & 0xF0FF) == 0x406A)
        {
            ins.op = Op::LDS_PR_L;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // DT Rn (0x4n11)
        else if ((raw & 0xF0FF) == 0x4011)
        {
            ins.op = Op::DT;
            ins.dst.isImm = false;
            ins.dst.reg = n; // Rn is the register to decrement and test
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHLL2/8/16 Rn  (0x4n08,0x4n18,0x4n28)
        else if ((raw & 0xF00F) == 0x4008)
        {
            uint8_t sub = (raw >> 4) & 0xF; // bits 7-4 determine variant
            uint8_t shift = 0;
            switch (sub)
            {
            case 0x0: shift = 2; break;   // 0x4n08
            case 0x1: shift = 8; break;   // 0x4n18
            case 0x2: shift = 16; break;  // 0x4n28
            default: shift = 1; break; // fallback
            }
            ins.op = Op::SHL;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.extra = shift;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B @Rm,Rn  (0x6nm0)   sign-extended byte load
        else if ((raw & 0xF00F) == 0x6000)
        {
            ins.op = Op::LOAD8;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = false;
            ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.L @Rm,Rn (0x6nm2)
        else if ((raw & 0xF00F) == 0x6002 && m != 0)
        {
            ins.op = Op::LOAD32;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.B @Rm+,Rn (0x6nm4)
        else if ((raw & 0xF00F) == 0x6004)
        {
            ins.op = Op::LOAD8_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.W @Rm+,Rn (0x6nm5)
        else if ((raw & 0xF00F) == 0x6005)
        {
            ins.op = Op::LOAD16_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L @Rm+,Rn (0x6nm6)
        else if ((raw & 0xF00F) == 0x6006)
        {
            ins.op = Op::LOAD32_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
            INFO_LOG(SH4, "Emitter::CreateNew: Manually decoded MOV.L @R%d+,R%d (0x%04X) at PC=0x%08X", m, n, raw, pc);
        }
        // DT Rn (0x4n11)
        else if ((raw & 0xF0FF) == 0x4011)
        {
            ins.op = Op::DT;
            ins.dst = {false, n}; // Rn is in bits 11-8, already extracted as 'n'
            ins.dst.type = RegType::GPR; // Explicitly GPR
            blk.pcNext = pc + 2;   // DT is not a branch
            decoded = true;
            INFO_LOG(SH4, "Emitter::CreateNew: Manually decoded DT R%d (0x%04X) at PC=0x%08X", n, raw, pc);
        }
        // MOV.L @(disp,Rm),Rn (0x5nm2)
        else if ((raw & 0xF00F) == 0x5002)
        {
            ins.op = Op::LOAD32; // Generic load, displacement in ins.extra
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = (raw & 0xF) * 4; // disp is lower 4 bits, scaled by 4
            decoded = true; blk.pcNext = pc + 2;
            INFO_LOG(SH4, "Emitter::CreateNew: Manually decoded MOV.L @(0x%X,R%d),R%d (0x%04X) at PC=0x%08X", ins.extra, m, n, raw, pc);
        }
        // NEG Rm -> Rn  (0x6nmB)
        else if ((raw & 0xF00F) == 0x600B)
        {
            ins.op = Op::NEG;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // EXTU.B Rm -> Rn  (0x6nmC)
        else if ((raw & 0xF00F) == 0x600C)
        {
            ins.op = Op::EXTU_B;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // EXTS.B Rm -> Rn  (0x6nmD)
        else if ((raw & 0xF00F) == 0x600D)
        {
            ins.op = Op::EXTS_B;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // EXTU.W Rm -> Rn  (0x6nmE)
        else if ((raw & 0xF00F) == 0x600E)
        {
            ins.op = Op::EXTU_W;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // EXTS.W Rm -> Rn  (0x6nmF)
        else if ((raw & 0xF00F) == 0x600F)
        {
            ins.op = Op::EXTS_W;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.B Rm,@Rn  (0x2nm0)
        else if ((raw & 0xF00F) == 0x2000)
        {
            ins.op = Op::STORE8;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L Rm,@Rn  (0x2nm2)
        else if ((raw & 0xF00F) == 0x2002)
        {
            ins.op = Op::STORE32;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.W Rm,@Rn+ (0x2nm5)
        else if ((raw & 0xF00F) == 0x2005)
        {
            ins.op = Op::STORE16_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L Rm,@Rn+ (0x2nm6)
        else if ((raw & 0xF00F) == 0x2006)
        {
            ins.op = Op::STORE32_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // CMP/EQ Rm,Rn  (0x3nm0)
        else if ((raw & 0xF00F) == 0x3000)
        {
            ins.op = Op::CMP_EQ;
            ins.dst.isImm = false; ins.dst.reg = n; // Rn
            ins.src1.isImm = false; ins.src1.reg = m; // Rm
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // CMP/HI Rm,Rn (0x3nm6)
        else if ((raw & 0xF00F) == 0x3006)
        {
            ins.op = Op::CMP_HI;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // CMP/HS Rm,Rn (0x3nm2)
        else if ((raw & 0xF00F) == 0x3002)
        {
            ins.op = Op::CMP_HS;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // CMP/GE Rm,Rn (0x3nm3)
        else if ((raw & 0xF00F) == 0x3003)
        {
            ins.op = Op::CMP_GE;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // CMP/GT Rm,Rn (0x3nm7)
        else if ((raw & 0xF00F) == 0x3007)
        {
            ins.op = Op::CMP_GT;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // SUB Rm,Rn (0x3nm8)
        else if ((raw & 0xF00F) == 0x3008)
        {
            ins.op = Op::SUB;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // ADDC Rm,Rn (0x3nmC) Add with carry
        else if ((raw & 0xF00F) == 0x300C)
        {
            ins.op = Op::ADDC;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // CMP/PL Rn (0x4n05)
        else if ((raw & 0xF0FF) == 0x4005)
        {
            ins.op = Op::CMP_PL;
            ins.src1.isImm = false; ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // TST #imm8,R0  (0xC8??)
        else if ((raw & 0xFF00) == 0xC800)
        {
            ins.op = Op::TST_IMM;
            ins.src1.isImm = true; ins.src1.imm = raw & 0xFF;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOVT Rn (0x6n02) — requires m == 0
        else if ((raw & 0xF0FF) == 0x6002 && m == 0)
        {
            ins.op = Op::MOVT;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // BF disp8 (no delay) 0x8B??
        else if ((raw & 0xFF00) == 0x8B00)
        {
            int8_t disp = raw & 0xFF;
            int32_t d = static_cast<int32_t>(disp) << 1;
            ins.op = Op::BF;
            ins.extra = d;
            decoded = true;
            blk.pcNext = pc + 2; // no delay slot
        }
        // BF/S disp8 (with delay slot) 0x8F??
        else if ((raw & 0xFF00) == 0x8F00)
        {
            int8_t disp = raw & 0xFF;
            int32_t d = static_cast<int32_t>(disp) << 1;
            ins.op = Op::BF_S;
            ins.extra = d;
            decoded = true;
            blk.pcNext = pc + 4; // executes delay slot
        }
        // BT disp8 (no delay) 0x8900
        else if ((raw & 0xFF00) == 0x8900)
        {
            int8_t disp = raw & 0xFF;
            int32_t d = static_cast<int32_t>(disp) << 1;
            ins.op = Op::BT;
            ins.extra = d;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // BT/S disp8 (with delay slot) 0x8D??
        else if ((raw & 0xFF00) == 0x8D00)
        {
            int8_t disp = raw & 0xFF;
            int32_t d = static_cast<int32_t>(disp) << 1;
            ins.op = Op::BT_S;
            ins.extra = d;
            decoded = true;
            blk.pcNext = pc + 4;
        }
        // RTE (return from exception, has delay slot) 0x002B
        else if (raw == 0x002B)
        {
            ins.op = Op::RTE;
            decoded = true;
            blk.pcNext = pc + 4; // one delay slot
        }
        // MOV.W @(disp,PC),Rn  (0x9000 | Rn<<8 | disp8)
        else if ((raw & 0xF000) == 0x9000)
        {
            uint8_t disp = raw & 0xFF;
            uint32_t addr = (pc + 4) + (disp << 1);
            ins.op = Op::LOAD16_IMM;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = true;
            ins.src1.imm = addr;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // LDC.L @Rm+, <CR> (0x4mc7, where 'c' is control reg index, 'm' is GPR Rm for address)
        // SR(c=0), GBR(c=1), VBR(c=2), SSR(c=3), SPC(c=4),
        // Rn_BANK(c=5, actual bank reg in bits 3-0 of opcode),
        // SGR(c=6), DBR(c=7)
        else if ((raw & 0xF00F) == 0x4007) // Matches 0x4mc7 pattern
        {
            ins.op = Op::LDC_L;
            ins.src1.isImm = false;
            ins.src1.reg = (raw >> 8) & 0xF;    // Rm (source GPR for address, post-incremented)
            uint8_t c_val = (raw >> 4) & 0xF;    // c-field from opcode (control register category)

            if (c_val == 5) // LDC.L @Rm+, Rn_BANK (opcode 0x4m5d7, d = bank reg index 0-7)
            {
                ins.extra = 8 + (raw & 0x7); // R0_BANK -> 8, ..., R7_BANK -> 15
            }
            else
            {
                ins.extra = c_val;
            }
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.L @(disp,PC),Rn  (0xD000 | Rn<<8 | disp8)
        else if ((raw & 0xF000) == 0xD000)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::LOAD32_PC;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.extra = disp; // keep raw disp8 for executor to use
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // JSR @Rn  (0x4n0B) – operand register is 'n' (bits 11-8)
        else if ((raw & 0xF0FF) == 0x400B)
        {
            ins.op = Op::JSR;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 4;
        }
        // JMP @Rn  (0x4n2B) – operand register is 'n'
        else if ((raw & 0xF0FF) == 0x402B)
        {
            ins.op = Op::JMP;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 4;
        }
        // RTS (0x000B)
        else if (raw == 0x000B)
        {
            ins.op = Op::RTS;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SWAP.B Rm,Rn 0x6nm8
        else if ((raw & 0xF00F) == 0x6008)
        {
            ins.op = Op::SWAP_B;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SWAP.W Rm,Rn 0x6nm9
        else if ((raw & 0xF00F) == 0x6009)
        {
            ins.op = Op::SWAP_W;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // AND Rm,Rn 0x2nm9
        else if ((raw & 0xF00F) == 0x2009)
        {
            ins.op = Op::AND_REG;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;            decoded = true;
            blk.pcNext = pc + 2;
        }
        // TST Rm,Rn 0x2nm8
        else if ((raw & 0xF00F) == 0x2008)
        {
            ins.op = Op::TST_REG;
            ins.dst.isImm = false; ins.dst.reg = n; // Rn is first operand (same as AND)
            ins.src1.isImm = false; ins.src1.reg = m; // Rm
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // XOR Rm,Rn 0x2nmA
        else if ((raw & 0xF00F) == 0x200A)
        {
            ins.op = Op::XOR_REG;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // OR Rm,Rn 0x2nmB
        else if ((raw & 0xF00F) == 0x200B)
        {
            ins.op = Op::OR_REG;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // NOT Rm,Rn 0x6nm7
        else if ((raw & 0xF00F) == 0x6007)
        {
            ins.op = Op::NOT_OP;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // DT Rn 0x4010
        else if ((raw & 0xF0FF) == 0x4010)
        {
            ins.op = Op::DT;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHLL Rn (shift left 1) 0x4000
        else if ((raw & 0xF0FF) == 0x4000)
        {
            ins.op = Op::SHL1;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHLR Rn 0x4001
        else if ((raw & 0xF0FF) == 0x4001)
        {
            ins.op = Op::SHR1;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHAL Rn 0x4020 (same as SHL1)
        else if ((raw & 0xF0FF) == 0x4020)
        {
            ins.op = Op::SHL1;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHAR Rn 0x4021
        else if ((raw & 0xF0FF) == 0x4021)
        {
            ins.op = Op::SAR1;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHLD Rm,Rn 0x4nmD (shift left double, uses Rm low 16 bits)
        else if ((raw & 0xF00F) == 0x400D)
        {
            ins.op = Op::SHLD;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // ROTL Rn 0x4004
        else if ((raw & 0xF0FF) == 0x4004)
        {
            ins.op = Op::SHL; // reuse SHL with extra=1 but wrap-around later in exec
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.extra = 1 | 0x80; // flag 0x80 indicates rotate
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // ROTR Rn 0x4005
        else if ((raw & 0xF0FF) == 0x4005)
        {
            ins.op = Op::SHR_OP; // treat as right rotate 1 using flag
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.extra = 1 | 0x80;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // AND #imm8,R0 0xC9??
        else if ((raw & 0xFF00) == 0xC900)
        {
            ins.op = Op::AND_IMM;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = true; ins.src1.imm = raw & 0xFF;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // XOR #imm8,R0 0xCA??
        else if ((raw & 0xFF00) == 0xCA00)
        {
            ins.op = Op::XOR_IMM;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = true; ins.src1.imm = raw & 0xFF;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // OR #imm8,R0 0xCB??
        else if ((raw & 0xFF00) == 0xCB00)
        {
            ins.op = Op::OR_IMM;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = true; ins.src1.imm = raw & 0xFF;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B R0,@(disp,GBR) 0xC0??
        else if ((raw & 0xFF00) == 0xC000)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::STORE8_GBR;
            ins.src1.isImm = false; ins.src1.reg = 0; // R0 value
            ins.extra = disp; // byte offset
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.W R0,@(disp,GBR) 0xC1??
        else if ((raw & 0xFF00) == 0xC100)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::STORE16_GBR;
            ins.src1.isImm = false; ins.src1.reg = 0;
            ins.extra = disp << 1;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L R0,@(disp,GBR) 0xC2??
        else if ((raw & 0xFF00) == 0xC200)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::STORE32_GBR;
            ins.src1.isImm = false; ins.src1.reg = 0;
            ins.extra = disp << 2;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.B @(disp,GBR),R0 0xC4??
        else if ((raw & 0xFF00) == 0xC400)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::LOAD8_GBR;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.extra = disp;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.W @(disp,GBR),R0 0xC5??
        else if ((raw & 0xFF00) == 0xC500)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::LOAD16_GBR;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.extra = disp << 1;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L @(disp,GBR),R0 0xC6??
        else if ((raw & 0xFF00) == 0xC600)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::LOAD32_GBR;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.extra = disp << 2;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOVA @(disp,PC),R0 0xC7??
        else if ((raw & 0xFF00) == 0xC700)
        {
            uint8_t disp = raw & 0xFF;
            uint32_t imm = ((pc & ~3u) + 4) + (disp << 2);
            ins.op = Op::MOVA;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = true; ins.src1.imm = imm;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L @(disp,Rm),Rn 0x5nmd  (Rm = m, disp = low4*4). Covers all Rm values, including R0.
        else if ((raw & 0xF000) == 0x5000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::LOAD32;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = false;
            ins.src1.reg = m;   // base register Rm (bits 7-4)
            ins.extra = disp4 * 4; // byte displacement
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B @(disp,Rm),Rn 0x8nmd (disp=low4)
        else if ((raw & 0xF000) == 0x8000 && (raw & 0x0F00) != 0x0400 && (raw & 0x0F00) != 0x0500 && (raw & 0x0F00) != 0x0600)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::LOAD8;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.W @(disp,Rm),Rn 0x9nmd (disp=low4*2)
        else if ((raw & 0xF000) == 0x9000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::LOAD16;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4 * 2;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // JSR @(disp,PC) case was erroneously matched by 0xA000 earlier. The SH-4 ISA does NOT have such an instruction;
        // JSR is register-indirect (pattern 0x4nmB). Therefore the previous block decoding 0xA000 as JSR has been removed.
        // SHLR2/8/16 Rn : 0x4n09,0x4n19,0x4n29
        else if ((raw & 0xF00F) == 0x4009)
        {
            uint8_t idx = (raw >> 4) & 0xF; // middle nibble determines amount
            int shift = (idx == 0) ? 2 : (idx == 1 ? 8 : 16);
            ins.op = Op::SHR_OP;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.extra = shift;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SAR2/8/16 Rn : 0x4n0A, 0x4n1A, 0x4n2A (arithmetic right shift)
        else if ((raw & 0xF00F) == 0x400A)
        {
            uint8_t idx = (raw >> 4) & 0xF;
            int shift = (idx == 0) ? 2 : (idx == 1 ? 8 : 16);
            ins.op = Op::SAR_OP;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.extra = shift;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // NOP (all-zero word)
        else if (raw == 0x0000)
        {
            ins.op = Op::NOP;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // NOP (No operation)
        else if (raw == 0x0009)
        {
            ins.op = Op::NOP;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B @(disp,Rm),R0 0x0nmd (disp = low4)  — allow n=0 too (except 0x0000 and 0x0009)
        else if ((raw & 0xF000) == 0x0000)
        {
            if (raw != 0x0000 && raw != 0x0009) // exclude NOP variants
            {
                uint8_t disp4 = raw & 0xF;
                uint8_t n_reg = (raw >> 8) & 0xF;
                uint8_t m_reg = (raw >> 4) & 0xF;
                ins.op = Op::STORE8;
                ins.dst.isImm = false; ins.dst.reg = n_reg; // base
                ins.src1.isImm = false; ins.src1.reg = m_reg; // value
                ins.extra = disp4; // byte offset
                decoded = true; blk.pcNext = pc + 2;
            }
        }
        // MOV.W Rm,@(disp,Rn) 0x1nmd (disp=low4*2)
        else if ((raw & 0xF000) == 0x1000 && (raw & 0x0F00) != 0x0000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::STORE16;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4 * 2;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.L Rm,@(disp,Rn) 0x4nmd (disp=low4*4)
        else if ((raw & 0xF000) == 0x4000 && (raw & 0x0F00) != 0x0000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::STORE32;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4 * 4;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // LDC Rm, <CR> (0x4mcE, where 'c' is control reg index, 'm' is source GPR Rm)
        // SR(c=0), GBR(c=1), VBR(c=2), SSR(c=3), SPC(c=4),
        // Rn_BANK(c=5, actual bank reg in bits 3-0 of opcode),
        // SGR(c=6), DBR(c=7)
        else if ((raw & 0xF00F) == 0x400E) // Matches 0x4mcE pattern
        {
            ins.op = Op::LDC;
            ins.src1.isImm = false;
            ins.src1.reg = (raw >> 8) & 0xF;    // Rm (source GPR)
            uint8_t c_val = (raw >> 4) & 0xF;    // c-field from opcode (control register category)

            if (c_val == 5) // LDC Rm, Rn_BANK (opcode 0x4m5dE, d = bank reg index 0-7)
            {
                // For Rn_BANK, the specific bank register (0-7) is in raw bits 3-0.
                // Map this to extra = 8 + (bank_reg_idx from bits 3-0 of opcode)
                ins.extra = 8 + (raw & 0x7); // R0_BANK -> 8, ..., R7_BANK -> 15
            }
            else
            {
                // For SR, GBR, VBR, SSR, SPC, SGR, DBR, c_val is directly used.
                // c_val will be 0, 1, 2, 3, 4, 6, or 7.
                ins.extra = c_val;
            }
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // CMP/STR Rm,Rn 0x2nmE
        else if ((raw & 0xF00F) == 0x200E)
        {
            ins.op = Op::CMP_STR;
            ins.dst.isImm = false; ins.dst.reg = n; // use dst as Rn
            ins.src1.isImm = false; ins.src1.reg = m; // src as Rm
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // STS MACH,Rn 0x0n0A
        else if ((raw & 0x00FF) == 0x000A)
        {
            ins.op = Op::GET_MACH;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // STS MACL,Rn 0x0n1A
        else if ((raw & 0x00FF) == 0x001A)
        {
            ins.op = Op::GET_MACL;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // STS PR,Rn 0x0n2A
        else if ((raw & 0x00FF) == 0x002A)
        {
            ins.op = Op::GET_PR;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // STS.L PR,@-Rn  (0x4n22)
        else if ((raw & 0xF0FF) == 0x4022)
        {
            ins.op = Op::STS_PR_L;
            ins.dst.isImm = false; // Rn contains address
            ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // LDS.L @Rn+,PR  (0x4n26)
        else if ((raw & 0xF0FF) == 0x4026)
        {
            ins.op = Op::LDS_PR_L;
            ins.src1.isImm = false; // Rn is address register
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // LDC.L @Rn+,SSR  0x4n37
        else if ((raw & 0xF0FF) == 0x4037)
        {
            ins.op = Op::LDC_SSR_L;
            ins.src1.isImm = false;  // address in Rn
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // LDC.L @Rn+,SPC  0x4n47
        else if ((raw & 0xF0FF) == 0x4047)
        {
            ins.op = Op::LDC_SPC_L;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // LDC.L @Rn+,SGR  0x4n36
        else if ((raw & 0xF0FF) == 0x4036)
        {
            ins.op = Op::LDC_SGR_L;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // LDTLB (load TLB entry) 0x0038
        else if (raw == 0x0038)
        {
            ins.op = Op::LDTLB;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B Rm,@Rn+ (0x2nm4)
        else if ((raw & 0xF00F) == 0x2004)
        {
            ins.op = Op::STORE8_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // FPU single-precision arithmetic  (1111 nnnn mmmm xxxx)
        else if ((raw & 0xF000) == 0xF000)
        {
            uint8_t sub = raw & 0xF;    // low 4 bits give operation
            switch (sub)
            {
            case 0x0: ins.op = Op::FADD;    break; // FADD FRm,FRn
            case 0x1: ins.op = Op::FSUB;    break; // FSUB FRm,FRn
            case 0x2: ins.op = Op::FMUL;    break; // FMUL FRm,FRn
            case 0x3: ins.op = Op::FDIV;    break; // FDIV FRm,FRn
            case 0x4: ins.op = Op::FCMP_EQ; break; // FCMP/EQ FRm,FRn (sets SR.T)
            case 0x5: ins.op = Op::FCMP_GT; break; // FCMP/GT FRm,FRn (sets SR.T)
            case 0x6: // FSQRT FRn (square root of FRn)
                ins.op = Op::FSQRT;
                ins.dst.isImm = false; ins.dst.reg = n; // FRn is both src and dst
                break;
            case 0x7: // FABS FRm,FRn (absolute value)
                ins.op = Op::FABS;
                ins.dst.isImm = false; ins.dst.reg = n;
                ins.src1.isImm = false; ins.src1.reg = m;
                break;
            case 0x8: // FMOV.S @(R0,Rm),FRn
                ins.op = Op::FMOV_LOAD_R0;
                ins.dst.isImm = false; ins.dst.reg = n; // FRn
                ins.src1.isImm = false; ins.src1.reg = m; // Rm for address offset
                break;
            case 0x9: // FMOV.S FRm,@(R0,Rn)
                ins.op = Op::FMOV_STORE_R0;
                ins.dst.isImm = false; ins.dst.reg = n; // Rn provides offset for store address
                ins.src1.isImm = false; ins.src1.reg = m; // FRm source value register
                break;
            case 0xD: // FSTS FPUL, FRn (0xFnnD)
                ins.op = Op::FSTS;
                ins.src1.isImm = false;
                ins.src1.reg = (raw >> 8) & 0xF; // FRn
                ins.src1.type = RegType::FGR;
                // ins.dst is not used by executor for this op
                // FPUL is an implicit source for the executor
                INFO_LOG(SH4, "Emitter::CreateNew: Manually decoded FSTS FPUL,FR%d (0x%04X) at PC=0x%08X", ins.src1.reg, raw, pc);
                break;
            default:  ins.op = Op::ILLEGAL; break; // other 0xF subcodes not handled yet
            }
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.W @Rm,Rn (0x6nm1)
        else if ((raw & 0xF00F) == 0x6001)
        {
            ins.op = Op::LOAD16;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = 0;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.B @(disp,Rm),R0 0x84md
        else if ((raw & 0xFF00) == 0x8400)
        {
            uint8_t disp4 = raw & 0xF;
            uint8_t m_reg = (raw >> 4) & 0xF;
            ins.op = Op::LOAD8;
            ins.dst.isImm = false; ins.dst.reg = 0; // R0
            ins.src1.isImm = false; ins.src1.reg = m_reg;
            ins.extra = disp4; // byte displacement
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.W @(disp,Rm),R0 0x85md
        else if ((raw & 0xFF00) == 0x8500)
        {
            uint8_t disp4 = raw & 0xF;
            uint8_t m_reg = (raw >> 4) & 0xF;
            ins.op = Op::LOAD16;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = false; ins.src1.reg = m_reg;
            ins.extra = disp4 * 2;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L @(disp,Rm),R0 0x86md
        else if ((raw & 0xFF00) == 0x8600)
        {
            uint8_t disp4 = raw & 0xF;
            uint8_t m_reg = (raw >> 4) & 0xF;
            ins.op = Op::LOAD32;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = false; ins.src1.reg = m_reg;
            ins.extra = disp4 * 4;
            decoded = true; blk.pcNext = pc + 2;
        }


        // ----------------------------------------------------------------
        //  Fail-safe: if still not decoded, treat as NOP so execution
        //  continues instead of throwing an IllegalInstr exception that
        //  trips the fatal error inside BIOS padding or unknown areas.
        // ----------------------------------------------------------------
        if (!decoded)
        {
            ins.op = Op::ILLEGAL;
            decoded = true;
            blk.pcNext = pc + 2;
        }

        // If we decoded something (including NOP fallback), push instruction
        if (decoded)
        {
            blk.code.push_back(ins);

            INFO_LOG(SH4, "Emitter::CreateNew: Before delay slot check for PC=0x%08X, main_raw=0x%04X. blk.pcNext=0x%08X, expected_pc_plus_4=0x%08X", pc, raw, blk.pcNext, pc + 4);
            // If instruction has delay slot, append slot instruction
            if (blk.pcNext == pc + 4)
            {
                uint32_t slot_pc = pc + 2;
                uint16_t slot_raw = mmu_IReadMem16(slot_pc);
                Instr slot{};
                INFO_LOG(SH4, "Emitter::DelaySlot: Decoding for slot_pc=0x%08X, slot_raw=0x%04X", slot_pc, slot_raw);
                bool slot_decoded_fast = FastDecode(slot_raw, slot_pc, slot, blk);
                INFO_LOG(SH4, "Emitter::DelaySlot: FastDecode returned %d, slot.op=%d (expected MOV_REG=%d), blk.pcNext=0x%08X", slot_decoded_fast, static_cast<int>(slot.op), static_cast<int>(Op::MOV_REG), blk.pcNext);

                if (!slot_decoded_fast)
                {
                    // Attempt manual decode for the slot if FastDecode failed
                    // This is a simplified version; a more robust solution might involve calling a subset of manual decoders
                    if ((slot_raw & 0xF00F) == 0x6003) { // MOV_REG Rm, Rn (MOV R0,R2 -> 0x6023)
                        slot.op = Op::MOV_REG;
                        slot.dst.isImm = false; slot.dst.reg = (slot_raw >> 8) & 0xF; // Rn
                        slot.src1.isImm = false; slot.src1.reg = (slot_raw >> 4) & 0xF; // Rm
                        INFO_LOG(SH4, "Emitter::DelaySlot: Manually decoded MOV_REG (0x%04X) for slot. slot.op=%d", slot_raw, static_cast<int>(slot.op));
                    }
                    // FSTS FPUL, FRn (0xFnnB)
                    else if ((slot_raw & 0xF00F) == 0xF00B)
                    {
                        slot.op = Op::FSTS;
                        slot.src1.isImm = false; slot.src1.reg = (slot_raw >> 8) & 0xF; // FRn is in bits 11-8
                        // FPUL is implicit source/destination for FSTS
                        INFO_LOG(SH4, "Emitter::DelaySlot: Manually decoded FSTS FPUL, FR%d (0x%04X) for slot. slot.op=%d", slot.src1.reg, slot_raw, static_cast<int>(slot.op));
                    }
                     else {

                        slot.op = Op::ILLEGAL;
                        // If the delay slot itself causes a change in pcNext (e.g. another branch), that's complex and not handled here simply.
                        // For now, assume delay slot is simple and doesn't alter flow beyond what main branch dictates.
                        // However, if it's truly illegal, the block's pcNext might need to point after the illegal slot instruction.
                        // This was: blk.pcNext = slot_pc + 2; - let's see if removing it helps, relying on main branch's pcNext.
                        INFO_LOG(SH4, "Emitter::DelaySlot: Slot instruction 0x%04X at 0x%08X is ILLEGAL after FastDecode failed.", slot_raw, slot_pc);
                    }
                }
                blk.code.push_back(slot);
                INFO_LOG(SH4, "Emitter::DelaySlot: Pushed slot.op=%d. Final blk.pcNext for main block (PC=0x%08X) is 0x%08X", static_cast<int>(slot.op), pc, blk.pcNext);
            }

            Instr end{}; end.op = Op::END;
            blk.code.push_back(end);
            g_block_sig_cache.emplace(sig, &blk);
            return blk;
        }
    }
    return blk;
}

const Block* Emitter::BuildBlock(uint32_t pc)
{
    auto it = cache_.find(pc);
    if (it != cache_.end())
        return &it->second;
    return &CreateNew(pc);
}

void Emitter::EmitInstr(Block&, uint16_t) {
    // TODO: real decode later
}

} // namespace ir
} // namespace sh4
