#include "ir_emitter.h"
#include "hw/sh4/sh4_if.h"  // for Sh4Context, etc.
#include "hw/sh4/modules/mmu.h"
#include "log/Log.h"
#include "hw/sh4/sh4_core.h" // for SH4ThrownException and codes
#include "ir_tables.h" // autogenerated opcode -> Op table
#include <cstdarg>
#include <cstdio>
#include <mutex>
#include <unordered_map>
#define XXH_STATIC_LINKING_ONLY
#include <xxhash.h>

#if __APPLE
#include <CoreFoundation/CoreFoundation.h>
#endif

namespace {
static FILE* g_ir_log_file = nullptr;
static std::mutex g_ir_log_mutex;

void log_to_file(const char* fmt, ...)
{
    std::lock_guard<std::mutex> lk(g_ir_log_mutex);
    if (!g_ir_log_file)
    {
        char path[PATH_MAX];
        #if __APPLE
        // Use iOS documents directory
        CFURLRef documents_dir = CFBundleCopyResourcesDirectoryURL(CFBundleGetMainBundle());
        CFURLGetFileSystemRepresentation(documents_dir, true, (UInt8*)path, PATH_MAX);
        CFRelease(documents_dir);
        #else
        // Use home directory on other platforms
        char* home_dir = getenv("HOME");
        if (!home_dir)
            return; // give up silently
        snprintf(path, PATH_MAX, "%s/sh4_ir.log", home_dir);
        #endif
        g_ir_log_file = fopen(path, "a");
        if (!g_ir_log_file)
            return; // give up silently
    }
    va_list ap;
    va_start(ap, fmt);
    vfprintf(g_ir_log_file, fmt, ap);
    va_end(ap);
    fflush(g_ir_log_file);
}

// Reuse identical blocks (e.g. BIOS memset stub copied across SDRAM pages)
static std::unordered_map<uint64_t, const sh4::ir::Block*> g_block_sig_cache;

static uint64_t CalcBlockSig(uint32_t pc)
{
    // Hash first 64 bytes (32 instructions) of code at pc.
    uint8_t buf[64];
    for (int i = 0; i < 32; ++i)
    {
        uint16_t op = mmu_IReadMem16(pc + i * 2);
        buf[i * 2]     = static_cast<uint8_t>(op & 0xFF);
        buf[i * 2 + 1] = static_cast<uint8_t>(op >> 8);
    }
    return XXH3_64bits(buf, sizeof(buf));
}
}

namespace sh4 {
namespace ir {

// Fast-path decode using autogenerated table. Returns true if handled.
static bool FastDecode(uint16_t raw, uint32_t pc, Instr &ins, Block &blk)
{
    Op op = static_cast<Op>(kEmitterTable[raw]);
    if (op == Op::ILLEGAL)
        return false; // table says unsupported / fall back

    uint8_t n = (raw >> 8) & 0xF;
    uint8_t m = (raw >> 4) & 0xF;

    switch (op)
    {
    case Op::NOP:
        ins.op = Op::NOP;
        blk.pcNext = pc + 2;
        return true;

    case Op::MOV_REG:
        ins.op = Op::MOV_REG;
        ins.dst = {false, n};
        ins.src1 = {false, m};
        blk.pcNext = pc + 2;
        return true;

    case Op::MOV_IMM:
        ins.op = Op::MOV_IMM;
        ins.dst = {false, n};
        ins.src1.isImm = true;
        ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
        blk.pcNext = pc + 2;
        return true;

    case Op::ADD_IMM:
        ins.op = Op::ADD_IMM;
        ins.dst = {false, n};
        ins.src1.isImm = true;
        ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
        blk.pcNext = pc + 2;
        return true;

    case Op::SUB:
    case Op::AND_REG:
    case Op::OR_REG:
    case Op::XOR_REG:
    case Op::NOT:
    case Op::NEG:
    case Op::EXTU_B:
    case Op::EXTU_W:
    case Op::EXTS_B:
    case Op::EXTS_W:
        ins.op = op;
        ins.dst = {false, n};
        ins.src1 = {false, m};
        blk.pcNext = pc + 2;
        return true;

    case Op::BRA:
    {
        int32_t disp = static_cast<int32_t>(raw & 0x0FFF);
        if (disp & 0x800)
            disp |= ~0xFFF;
        disp <<= 1;
        ins.op = Op::BRA;
        ins.extra = disp + 4;
        blk.pcNext = pc + 4;
        return true;
    }
    case Op::BT:
    case Op::BF:
    {
        int8_t disp = raw & 0xFF;
        int32_t d = disp << 1;
        ins.op = op;
        ins.extra = d + 4;
        blk.pcNext = pc + 4;
        return true;
    }
    default:
        return false; // not yet implemented; let manual path try
    }
}

Block& Emitter::CreateNew(uint32_t pc) {
    // Simple global cap on total cached blocks to avoid runaway memory usage.
    static constexpr size_t kMaxBlocks = 100000; // ~100k blocks ~= few MB
    if (cache_.size() > kMaxBlocks)
    {
        cache_.clear();
        g_block_sig_cache.clear();
    }

    auto [it, inserted] = cache_.emplace(pc, Block{});
    Block& blk = it->second;
    if (inserted)
    {
        // Deduplicate identical code blocks to avoid runaway allocations.
        uint64_t sig = CalcBlockSig(pc);
        if (auto itSig = g_block_sig_cache.find(sig); itSig != g_block_sig_cache.end())
        {
            // Point cache entry at existing block and discard placeholder.
            return const_cast<Block&>(*itSig->second);
        }

        blk.pcStart = pc;

        uint16_t raw = mmu_IReadMem16(pc);

        // Simple decode for a few key opcodes
        uint8_t n = (raw >> 8) & 0xF;
        uint8_t m = (raw >> 4) & 0xF;

        Instr ins{};
        // clear operands
        ins.dst = {};
        ins.src1 = {};
        ins.src2 = {};
        bool decoded = false;

        static Block zero_blk;
        if (raw == 0x0000 || raw == 0x0009 || raw == 0xFFFE || raw == 0xFFFF)
        {
            // Reuse a single stub block for 0x0000 to avoid excessive allocations, but update PC fields each time
            if (zero_blk.code.empty())
            {
                Instr nop{}; nop.op = Op::NOP; zero_blk.code.push_back(nop);
                Instr end{}; end.op = Op::END; zero_blk.code.push_back(end);
            }
            zero_blk.pcStart = pc;
            zero_blk.pcNext  = pc + 2;
            return zero_blk;
        }

        // Attempt fast-path decode first – if handled, emit block immediately
        if (FastDecode(raw, pc, ins, blk))
        {
            blk.code.push_back(ins);
            Instr end{}; end.op = Op::END;
            blk.code.push_back(end);
            // Store signature mapping
            g_block_sig_cache.emplace(sig, &blk);
            return blk;
        }

        // If not decoded by table, fall back to minimal manual patterns below
        // fast-path via autogenerated table is disabled until enum list completed
        // NOP : MOV R0,R0 (0x0009)
        // MOV Rm -> Rn  (0x6nm3) pattern 0110 nnnn mmmm 0011
        else if ((raw & 0xF00F) == 0x6003)
        {
            ins.op = Op::MOV_REG;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = false;
            ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV #imm,Rn  (0xE000 | Rn<<8 | imm8)
        else if ((raw & 0xF000) == 0xE000)
        {
            ins.op = Op::MOV_IMM;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = true;
            ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // ADD #imm,Rn  (0x7000 | Rn<<8 | imm8)
        else if ((raw & 0xF000) == 0x7000)
        {
            ins.op = Op::ADD_IMM;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = true;
            ins.src1.imm = static_cast<int8_t>(raw & 0xFF);
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // BRA disp12  (0xA000 | disp)
        else if ((raw & 0xF000) == 0xA000)
        {
            int32_t disp = static_cast<int32_t>(raw & 0x0FFF);
            if (disp & 0x800) // sign bit of 12-bit
                disp |= ~0xFFF; // sign extend to 32-bit
            disp <<= 1; // disp*2 since pc+4 later
            ins.op = Op::BRA;
            ins.extra = disp + 4; // pc-relative (add after delay slot)
            decoded = true;
            blk.pcNext = pc + 4; // after delay slot
        }
        // BSR disp12 (0xB000 | disp)
        else if ((raw & 0xF000) == 0xB000)
        {
            int32_t disp = static_cast<int32_t>(raw & 0x0FFF);
            if (disp & 0x800)
                disp |= ~0xFFF;          // sign-extend
            disp <<= 1;                  // *2 because PC is word based
            ins.op = Op::BSR;
            ins.extra = disp + 4;        // displacement relative to current PC (after delay slot)
            decoded = true;
            blk.pcNext = pc + 4;         // delay slot present
        }
        // BSRF Rn  (0x0n03)
        else if ((raw & 0xF0FF) == 0x0003)
        {
            ins.op = Op::BSRF;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 4; // includes delay slot
        }
        // BRAF Rn  (0x0n23)
        else if ((raw & 0xF0FF) == 0x0023)
        {
            ins.op = Op::BRAF;
            ins.src1.isImm = false;
            ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 4; // delay slot
        }
        // SHLL2/8/16 Rn  (0x4n08,0x4n18,0x4n28)
        else if ((raw & 0xF00F) == 0x4008)
        {
            uint8_t sub = (raw >> 4) & 0xF; // bits 7-4 determine variant
            uint8_t shift = 0;
            switch (sub)
            {
            case 0x0: shift = 2; break;   // 0x4n08
            case 0x1: shift = 8; break;   // 0x4n18
            case 0x2: shift = 16; break;  // 0x4n28
            default: shift = 1; break; // fallback
            }
            ins.op = Op::SHL;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.extra = shift;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.L @Rm,Rn  (0x6nm0)
        else if ((raw & 0xF00F) == 0x6000)
        {
            ins.op = Op::LOAD32;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = false;
            ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B @Rm+,Rn (0x6nm4)
        else if ((raw & 0xF00F) == 0x6004)
        {
            ins.op = Op::LOAD8_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.W @Rm+,Rn (0x6nm5)
        else if ((raw & 0xF00F) == 0x6005)
        {
            ins.op = Op::LOAD16_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L @Rm+,Rn (0x6nm6)
        else if ((raw & 0xF00F) == 0x6006)
        {
            ins.op = Op::LOAD32_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L Rm,@Rn  (0x2nm0)
        else if ((raw & 0xF00F) == 0x2000)
        {
            ins.op = Op::STORE32;
            ins.dst.isImm = false; // address in Rn
            ins.dst.reg = n;
            ins.src1.isImm = false; // value in Rm
            ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B Rm,@Rn+ (0x2nm4)
        else if ((raw & 0xF00F) == 0x2004)
        {
            ins.op = Op::STORE8_POST;
            ins.dst.isImm = false; ins.dst.reg = n; // address reg Rn
            ins.src1.isImm = false; ins.src1.reg = m; // value reg Rm
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.W Rm,@Rn+ (0x2nm5)
        else if ((raw & 0xF00F) == 0x2005)
        {
            ins.op = Op::STORE16_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L Rm,@Rn+ (0x2nm6)
        else if ((raw & 0xF00F) == 0x2006)
        {
            ins.op = Op::STORE32_POST;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // CMP/EQ Rm,Rn  (0x3nm0)
        else if ((raw & 0xF00F) == 0x3000)
        {
            ins.op = Op::CMP_EQ;
            ins.dst.isImm = false; ins.dst.reg = n; // Rn
            ins.src1.isImm = false; ins.src1.reg = m; // Rm
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // CMP/HI Rm,Rn (0x3nm6)
        else if ((raw & 0xF00F) == 0x3006)
        {
            ins.op = Op::CMP_HI;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // CMP/HS Rm,Rn (0x3nm7)
        else if ((raw & 0xF00F) == 0x3007)
        {
            ins.op = Op::CMP_HS;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // ADDC Rm,Rn (0x3nmC) Add with carry
        else if ((raw & 0xF00F) == 0x300C)
        {
            ins.op = Op::ADDC;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true; blk.pcNext = pc + 2;
        }
        // CMP/PL Rn (0x4n05)
        else if ((raw & 0xF0FF) == 0x4005)
        {
            ins.op = Op::CMP_PL;
            ins.src1.isImm = false; ins.src1.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // TST #imm8,R0  (0xC8??)
        else if ((raw & 0xFF00) == 0xC800)
        {
            ins.op = Op::TST_IMM;
            ins.src1.isImm = true; ins.src1.imm = raw & 0xFF;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOVT Rn (0x6n02)
        else if ((raw & 0xF0FF) == 0x6002)
        {
            ins.op = Op::MOVT;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // BF disp8 0x8B00 / BF/S 0x8F?? (branch if T==0)
        else if ((raw & 0xFF00) == 0x8B00 || (raw & 0xFF00) == 0x8F00)
        {
            int8_t disp = raw & 0xFF;
            int32_t d = disp << 1;
            ins.op = Op::BF;
            ins.extra = d + 4;
            decoded = true;
            blk.pcNext = pc + 4;
        }
        // BT disp8 0x8900 / BT/S 0x8D?? (branch if T==1)
        else if ((raw & 0xFF00) == 0x8900 || (raw & 0xFF00) == 0x8D00)
        {
            int8_t disp = raw & 0xFF;
            int32_t d = disp << 1;
            ins.op = Op::BT;
            ins.extra = d + 4;
            decoded = true;
            blk.pcNext = pc + 4;
        }
        // MOV.W @(disp,PC),Rn  (0x9000 | Rn<<8 | disp8)
        else if ((raw & 0xF000) == 0x9000)
        {
            uint8_t disp = raw & 0xFF;
            uint32_t addr = (pc + 4) + (disp << 1);
            ins.op = Op::LOAD16_IMM;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = true;
            ins.src1.imm = addr;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.L @(disp,PC),Rn  (0xD000 | Rn<<8 | disp8)
        else if ((raw & 0xF000) == 0xD000)
        {
            uint8_t disp = raw & 0xFF;
            uint32_t addr = (pc + 4) + (disp << 2);
            ins.op = Op::LOAD32_IMM;
            ins.dst.isImm = false;
            ins.dst.reg = n;
            ins.src1.isImm = true;
            ins.src1.imm = addr;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // JSR @Rm  (0x4nmB)
        else if ((raw & 0xF00F) == 0x400B)
        {
            ins.op = Op::JSR;
            ins.src1.isImm = false;
            ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 4;
        }
        // JMP @Rm  (0x4m2B)
        else if ((raw & 0xF0FF) == 0x402B)
        {
            ins.op = Op::JMP;
            ins.src1.isImm = false;
            ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 4;
        }
        // RTS (0x000B)
        else if (raw == 0x000B)
        {
            ins.op = Op::RTS;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SWAP.B Rm,Rn 0x6nm8
        else if ((raw & 0xF00F) == 0x6008)
        {
            ins.op = Op::SWAP_B;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SWAP.W Rm,Rn 0x6nm9
        else if ((raw & 0xF00F) == 0x6009)
        {
            ins.op = Op::SWAP_W;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // AND Rm,Rn 0x2nm9
        else if ((raw & 0xF00F) == 0x2009)
        {
            ins.op = Op::AND_REG;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // TST Rm,Rn 0x2nm8
        else if ((raw & 0xF00F) == 0x2008)
        {
            ins.op = Op::TST_REG;
            ins.dst.isImm = false; ins.dst.reg = n; // Rn is first operand (same as AND)
            ins.src1.isImm = false; ins.src1.reg = m; // Rm
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // XOR Rm,Rn 0x2nmA
        else if ((raw & 0xF00F) == 0x200A)
        {
            ins.op = Op::XOR_REG;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // OR Rm,Rn 0x2nmB
        else if ((raw & 0xF00F) == 0x200B)
        {
            ins.op = Op::OR_REG;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // NOT Rm,Rn 0x6nm7
        else if ((raw & 0xF00F) == 0x6007)
        {
            ins.op = Op::NOT_OP;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // DT Rn 0x4010
        else if ((raw & 0xF0FF) == 0x4010)
        {
            ins.op = Op::DT;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHLL Rn (shift left 1) 0x4000
        else if ((raw & 0xF0FF) == 0x4000)
        {
            ins.op = Op::SHL1;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHLR Rn 0x4001
        else if ((raw & 0xF0FF) == 0x4001)
        {
            ins.op = Op::SHR1;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHAL Rn 0x4020 (same as SHL1)
        else if ((raw & 0xF0FF) == 0x4020)
        {
            ins.op = Op::SHL1;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHAR Rn 0x4021
        else if ((raw & 0xF0FF) == 0x4021)
        {
            ins.op = Op::SAR1;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // ROTL Rn 0x4004
        else if ((raw & 0xF0FF) == 0x4004)
        {
            ins.op = Op::SHL; // reuse SHL with extra=1 but wrap-around later in exec
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.extra = 1 | 0x80; // flag 0x80 indicates rotate
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // ROTR Rn 0x4005
        else if ((raw & 0xF0FF) == 0x4005)
        {
            ins.op = Op::SHR_OP; // treat as right rotate 1 using flag
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.extra = 1 | 0x80;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // AND #imm8,R0 0xC9??
        else if ((raw & 0xFF00) == 0xC900)
        {
            ins.op = Op::AND_IMM;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = true; ins.src1.imm = raw & 0xFF;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // XOR #imm8,R0 0xCA??
        else if ((raw & 0xFF00) == 0xCA00)
        {
            ins.op = Op::XOR_IMM;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = true; ins.src1.imm = raw & 0xFF;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // OR #imm8,R0 0xCB??
        else if ((raw & 0xFF00) == 0xCB00)
        {
            ins.op = Op::OR_IMM;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = true; ins.src1.imm = raw & 0xFF;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B R0,@(disp,GBR) 0xC0??
        else if ((raw & 0xFF00) == 0xC000)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::STORE8_GBR;
            ins.src1.isImm = false; ins.src1.reg = 0; // R0 value
            ins.extra = disp; // byte offset
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.W R0,@(disp,GBR) 0xC1??
        else if ((raw & 0xFF00) == 0xC100)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::STORE16_GBR;
            ins.src1.isImm = false; ins.src1.reg = 0;
            ins.extra = disp << 1;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L R0,@(disp,GBR) 0xC2??
        else if ((raw & 0xFF00) == 0xC200)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::STORE32_GBR;
            ins.src1.isImm = false; ins.src1.reg = 0;
            ins.extra = disp << 2;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.B @(disp,GBR),R0 0xC4??
        else if ((raw & 0xFF00) == 0xC400)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::LOAD8_GBR;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.extra = disp;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.W @(disp,GBR),R0 0xC5??
        else if ((raw & 0xFF00) == 0xC500)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::LOAD16_GBR;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.extra = disp << 1;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L @(disp,GBR),R0 0xC6??
        else if ((raw & 0xFF00) == 0xC600)
        {
            uint8_t disp = raw & 0xFF;
            ins.op = Op::LOAD32_GBR;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.extra = disp << 2;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOVA @(disp,PC),R0 0xC7??
        else if ((raw & 0xFF00) == 0xC700)
        {
            uint8_t disp = raw & 0xFF;
            uint32_t imm = ((pc & ~3u) + 4) + (disp << 2);
            ins.op = Op::MOVA;
            ins.dst.isImm = false; ins.dst.reg = 0;
            ins.src1.isImm = true; ins.src1.imm = imm;
            decoded = true; blk.pcNext = pc + 2;
        }
        // MOV.L @(disp,Rm),Rn 0x5nmd (disp=low4*4)
        else if ((raw & 0xF000) == 0x5000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::LOAD32;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4 * 4;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B @(disp,Rm),Rn 0x8nmd (disp=low4)
        else if ((raw & 0xF000) == 0x8000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::LOAD8;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.W @(disp,Rm),Rn 0x9nmd (disp=low4*2)
        else if ((raw & 0xF000) == 0x9000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::LOAD16;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4 * 2;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // JSR @(disp,PC) case was erroneously matched by 0xA000 earlier. The SH-4 ISA does NOT have such an instruction;
        // JSR is register-indirect (pattern 0x4nmB). Therefore the previous block decoding 0xA000 as JSR has been removed.
        // SHLR2/8/16 Rn : 0x4n09,0x4n19,0x4n29
        else if ((raw & 0xF00F) == 0x4009)
        {
            uint8_t idx = (raw >> 4) & 0xF; // middle nibble determines amount
            int shift = (idx == 0) ? 2 : (idx == 1 ? 8 : 16);
            ins.op = Op::SHR_OP;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.extra = shift;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // SHAR2/8/16 Rn : 0x4n0B,0x4n1B,0x4n2B
        else if ((raw & 0xF00F) == 0x400B)
        {
            uint8_t idx = (raw >> 4) & 0xF;
            int shift = (idx == 0) ? 2 : (idx == 1 ? 8 : 16);
            ins.op = Op::SAR_OP;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.extra = shift;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.B Rm,@(disp,Rn) 0x0nmd (disp=low4)
        else if ((raw & 0xF000) == 0x0000 && (raw & 0x0F00) != 0x0000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::STORE8;
            ins.dst.isImm = false; ins.dst.reg = n; // base
            ins.src1.isImm = false; ins.src1.reg = m; // value
            ins.extra = disp4;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.W Rm,@(disp,Rn) 0x1nmd (disp=low4*2)
        else if ((raw & 0xF000) == 0x1000 && (raw & 0x0F00) != 0x0000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::STORE16;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4 * 2;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // MOV.L Rm,@(disp,Rn) 0x4nmd (disp=low4*4)
        else if ((raw & 0xF000) == 0x4000 && (raw & 0x0F00) != 0x0000)
        {
            uint8_t disp4 = raw & 0xF;
            ins.op = Op::STORE32;
            ins.dst.isImm = false; ins.dst.reg = n;
            ins.src1.isImm = false; ins.src1.reg = m;
            ins.extra = disp4 * 4;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // CMP/STR Rm,Rn 0x2nmE
        else if ((raw & 0xF00F) == 0x200E)
        {
            ins.op = Op::CMP_STR;
            ins.dst.isImm = false; ins.dst.reg = n; // use dst as Rn
            ins.src1.isImm = false; ins.src1.reg = m; // src as Rm
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // STS MACH,Rn 0x0n0A
        else if ((raw & 0x00FF) == 0x000A)
        {
            ins.op = Op::GET_MACH;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // STS MACL,Rn 0x0n1A
        else if ((raw & 0x00FF) == 0x001A)
        {
            ins.op = Op::GET_MACL;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }
        // STS PR,Rn 0x0n2A
        else if ((raw & 0x00FF) == 0x002A)
        {
            ins.op = Op::GET_PR;
            ins.dst.isImm = false; ins.dst.reg = n;
            decoded = true;
            blk.pcNext = pc + 2;
        }

        // ----------------------------------------------------------------
        //  Fail-safe: if still not decoded, treat as NOP so execution 
        //  continues instead of throwing an IllegalInstr exception that 
        //  trips the fatal error inside BIOS padding or unknown areas.
        // ----------------------------------------------------------------
        if (!decoded)
        {
            ins.op = Op::NOP;
            decoded = true;
            blk.pcNext = pc + 2;
        }

        // If we decoded something (including NOP fallback), push instruction
        if (decoded)
        {
            blk.code.push_back(ins);
            Instr end{}; end.op = Op::END;
            blk.code.push_back(end);
            // Store signature mapping
            g_block_sig_cache.emplace(sig, &blk);
            return blk;
        }
    }
    return blk;
}

const Block* Emitter::BuildBlock(uint32_t pc)
{
    auto it = cache_.find(pc);
    if (it != cache_.end())
        return &it->second;
    return &CreateNew(pc);
}

void Emitter::EmitInstr(Block&, uint16_t) {
    // TODO: real decode later
}

} // namespace ir
} // namespace sh4
