#!/usr/bin/env python3
"""
gen_sh4_ir_tables.py – quick-and-dirty generator for Flycast's IR interpreter.

Reads core/hw/sh4/sh4_opcode_list.cpp (legacy table) and emits two C++ include
fragments:
    • ir_emitter_table.inc   // opcode -> Op enum name (or ILLEGAL)
    • ir_executor_table.inc  // opcode -> Exec helper function/lambda name

The legacy file already defines an OpCallFP* array `OpPtr` and an `OpDesc`
lookup with metadata (mnemonic, flags).  We mine these for the mnemonic so we
can map them directly to IR Op enum names following a simple rule:

    mnemonic "MOV.L"  -> enum string "MOV_L"
    mnemonic "ADD"    -> "ADD"
    mnemonic with slash ("CMP/HS") drops the slash -> "CMP_HS"

Anything we cannot match goes to ILLEGAL and will therefore fall back to the
legacy interpreter.

This is NOT a perfect parser – it relies on the fairly consistent formatting
of sh4_opcode_list.cpp.  Good enough to bootstrap – we can hand-fix corner
cases.
"""
import re
from pathlib import Path
import argparse
import sys

ROOT = Path(__file__).resolve().parents[1]  # project root (flycast-jitless)
LEGACY_SRC = ROOT / 'core/hw/sh4/sh4_opcode_list.cpp'
EMITTER_INC = ROOT / 'core/hw/sh4/ir/ir_emitter_table.inc'
EXECUTOR_INC = ROOT / 'core/hw/sh4/ir/ir_executor_table.inc'

# Match the initialization array entries:
# {0 , i0000..., Mask_n , 0x200C , Normal , "cmp/str <REG_M>,<REG_N>" , ...}
entry_re = re.compile(r'\{[^\}]*?,\s*0x([0-9A-Fa-f]{4})\s*,[^\}]*?"([^"]+)"')

def sanitize_mnemonic(text: str) -> str:
    # Take the part before space or tab, drop size suffix (.B/.W/.L etc.),
    # convert special chars to underscores.
    mnem = text.split()[0]
    mnem = mnem.replace('.', '_').replace('/', '_').replace('#', 'IMM')
    return mnem.upper()


def parse_legacy() -> dict:
    tbl = {}
    with open(LEGACY_SRC, 'r', encoding='utf-8') as f:
        for line in f:
            m = entry_re.search(line)
            if not m:
                continue
            op_hex = m.group(1)
            opcode = int(op_hex, 16)
            mnemonic_raw = m.group(2)
            mnemonic = sanitize_mnemonic(mnemonic_raw)
            # first occurrence wins; ignore duplicates with different mnemonic but same opcode value
            if opcode not in tbl:
                tbl[opcode] = mnemonic
    return tbl


def write_inc(path: Path, mapping: dict, kind: str):
    """kind is 'EMIT' or 'EXEC'"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write('// AUTO-GENERATED by tools/gen_sh4_ir_tables.py – DO NOT EDIT\n')
        f.write('#pragma once\n')
        f.write('// Mapping table: index = 16-bit opcode\n')
        f.write('static const Op kSh4IrTbl_%s[0x10000] = {\n' % kind)
        for op in range(0x10000):
            mnem = mapping.get(op, 'ILLEGAL')
            f.write('    /*%04X*/ Op::%s,%s' % (op, mnem, '\n' if (op & 15) == 15 else ' '))
        f.write('};\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--quiet', action='store_true')
    args = ap.parse_args()

    mapping = parse_legacy()
    write_inc(EMITTER_INC, mapping, 'EMIT')
    write_inc(EXECUTOR_INC, mapping, 'EXEC')

    if not args.quiet:
        print('Generated %s and %s' % (EMITTER_INC, EXECUTOR_INC))

if __name__ == '__main__':
    main()
